export const PAGE_SOURCE = 'aitoearn-web'

export const MessageType = {
  CHECK_PERMISSION_REQUEST: 'CHECK_PERMISSION_REQUEST',
  CHECK_PERMISSION_RESPONSE: 'CHECK_PERMISSION_RESPONSE',
  GET_VERSION_REQUEST: 'GET_VERSION_REQUEST',
  GET_VERSION_RESPONSE: 'GET_VERSION_RESPONSE',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_RESPONSE: 'LOGIN_RESPONSE',
  PUBLISH_REQUEST: 'PUBLISH_REQUEST',
  PUBLISH_PROGRESS: 'PUBLISH_PROGRESS',
  PUBLISH_COMPLETE: 'PUBLISH_COMPLETE',
  PUBLISH_ERROR: 'PUBLISH_ERROR',
  XHS_REQUEST: 'XHS_REQUEST',
  XHS_REQUEST_RESPONSE: 'XHS_REQUEST_RESPONSE',
  DOUYIN_REQUEST: 'DOUYIN_REQUEST',
  DOUYIN_REQUEST_RESPONSE: 'DOUYIN_REQUEST_RESPONSE',
  DOUYIN_INTERACTION: 'DOUYIN_INTERACTION',
  DOUYIN_INTERACTION_RESPONSE: 'DOUYIN_INTERACTION_RESPONSE',
  DOUYIN_DIRECT_MESSAGE: 'DOUYIN_DIRECT_MESSAGE',
  DOUYIN_DIRECT_MESSAGE_RESPONSE: 'DOUYIN_DIRECT_MESSAGE_RESPONSE',
  UNIFIED_INTERACTION: 'UNIFIED_INTERACTION',
  UNIFIED_INTERACTION_RESPONSE: 'UNIFIED_INTERACTION_RESPONSE',
}

export const RuntimeAction = {
  CHECK_PERMISSION: 'JUJING_CHECK_PERMISSION',
  GET_VERSION: 'JUJING_GET_VERSION',
  LOGIN: 'JUJING_LOGIN',
  XHS_REQUEST: 'JUJING_XHS_REQUEST',
  DOUYIN_REQUEST: 'JUJING_DOUYIN_REQUEST',
  DOUYIN_INTERACTION: 'JUJING_DOUYIN_INTERACTION',
  DOUYIN_DIRECT_MESSAGE: 'JUJING_DOUYIN_DIRECT_MESSAGE',
  UNIFIED_INTERACTION: 'JUJING_UNIFIED_INTERACTION',
  PUBLISH: 'JUJING_PUBLISH',
}

export const PLATFORM_ORIGINS = {
  douyin: 'https://www.douyin.com',
  xhs: 'https://edith.xiaohongshu.com',
}

export const REQUIRED_PERMISSIONS = ['cookies', 'tabs', 'storage']
