export {
  Material,
  MaterialFilter,
  MaterialGroup,
  MaterialMedia,
  MaterialStatus,
  MaterialType,
  Media,
  MediaGroup,
  MediaType,
  MediaUrlInfo,
  NewMaterial,
  NewMaterialGroup,
  NewMedia,
  PubRecord,
  PubStatus,
  PubType,
  UpdateMaterialGroup,
  UpMaterial,
} from '@yikart/aitoearn-server-shared'
