export const NatsApi = {
  manager: {
    manager: {
      createByAccount: 'manager.manager.createByAccount',
      getInfoByAccount: 'manager.manager.getInfoByAccount',
    },
  },
  user: {
    admin: {
      user: {
        list: 'user.admin.user.list',
        info: 'user.admin.user.info',
        upPortrait: 'user.admin.user.upPortrait',
      },
      vip: {
        addAllPoints: 'user.admin.vip.addAllPoints',
      },
    },
    vip: {
      set: 'user.vip.set',
      clear: 'user.vip.clear',
    },
    income: {
      deduct: 'user.income.deduct',
      info: 'user.income.info',
    },
    userWalletAccount: {
      create: 'user.userWalletAccount.create',
      delete: 'user.userWalletAccount.delete',
      update: 'user.userWalletAccount.update',
      info: 'user.userWalletAccount.info',
      list: 'user.userWalletAccount.list',
    },
  },
  account: {
    account: {
      getUserAccounts: 'account.account.getUserAccounts',
      getAccounts: 'account.account.getAccounts',
      getAccountInfoById: 'account.account.getAccountInfoById',
      updateAccountInfo: 'account.account.updateAccountInfo',
      updateAccountStatistics: 'account.account.updateAccountStatistics',
      updateAccountStatus: 'account.account.updateAccountStatus',
      getAccountListByIds: 'account.account.getAccountListByIds',
      getUserAccountCount: 'account.account.getUserAccountCount',
      deleteUserAccount: 'account.account.deleteUserAccount',
      deleteUserAccounts: 'account.account.deleteUserAccounts',
      getAccountByParam: 'account.account.getAccountByParam',
      listByType: 'account.group.listByType',
    },
    admin: {
      account: {
        list: 'account.admin.account.list',
      },
    },
    group: {
      create: 'account.group.create',
      deleteList: 'account.group.deleteList',
      getList: 'account.group.getList',
      update: 'account.group.update',
    },
  },
  plat: {
    publish: {
      create: 'plat.publish.create',
      del: 'plat.publish.del',
    },
    bilibili: {
      getHeader: 'plat.bilibili.getHeader',
      getAccountAuthInfo: 'plat.bilibili.getAccountAuthInfo',
      authUrl: 'plat.bilibili.authUrl',
      createAccountAndSetAccessToken:
        'plat.bilibili.createAccountAndSetAccessToken',
      videoInit: 'plat.bilibili.videoInit',
      uploadVideoPart: 'plat.bilibili.uploadVideoPart',
      videoComplete: 'plat.bilibili.videoComplete',
      coverUpload: 'plat.bilibili.coverUpload',
      uploadLitVideo: 'plat.bilibili.uploadLitVideo',
      archiveAddByUtoken: 'plat.bilibili.archiveAddByUtoken',
      archiveTypeList: 'plat.bilibili.archiveTypeList',
      getAuthInfo: 'plat.bilibili.getAuthInfo',
      archiveList: 'plat.bilibili.archiveList',
      userStat: 'plat.bilibili.userStat',
      arcStat: 'plat.bilibili.arcStat',
      arcIncStat: 'plat.bilibili.arcIncStat',
    },
    kwai: {
      authUrl: 'plat.kwai.authUrl',
      addKwaiAccount: 'plat.kwai.addKwaiAccount',
    },
    wxGzh: {
      getAccountAuthInfo: 'plat.wxPlat.getAccountAuthInfo',
      authUrl: 'plat.wxPlat.authUrl',
      videoInit: 'plat.wxPlat.videoInit',
      uploadVideoPart: 'plat.wxPlat.uploadVideoPart',
      videoComplete: 'plat.wxPlat.videoComplete',
      coverUpload: 'plat.wxPlat.coverUpload',
      uploadLitVideo: 'plat.wxPlat.uploadLitVideo',
      archiveAddByUtoken: 'plat.wxPlat.archiveAddByUtoken',
      archiveTypeList: 'plat.wxPlat.archiveTypeList',
      getAuthInfo: 'plat.wxPlat.getAuthInfo',
      archiveList: 'plat.wxPlat.archiveList',
      userStat: 'plat.wxPlat.userStat',
      arcStat: 'plat.wxPlat.arcStat',
      arcIncStat: 'plat.wxPlat.arcIncStat',
    },
    youtube: {
      getAccountAuthInfo: 'plat.youtube.getAccountAuthInfo',
      authUrl: 'plat.youtube.authUrl',
      setAccessToken: 'plat.youtube.setAccessToken',
      getAuthInfo: 'plat.youtube.getAuthInfo',
      isAuthorized: 'plat.youtube.isAuthorized',
      getVideoCategories: 'plat.youtube.getVideoCategories',
      getVideosList: 'plat.youtube.getVideosList',
      uploadVideo: 'plat.youtube.uploadVideo',
      initVideoUpload: 'plat.youtube.initVideoUpload',
      uploadVideoPart: 'plat.youtube.uploadVideoPart',
      videoComplete: 'plat.youtube.videoComplete',
    },
    pinterest: {
      getUserAccount: 'plat.pinterest.getUserAccount',
      createAdAccount: 'plat.pinterest.createAdAccount',
      getAdAccountById: 'plat.pinterest.getAdAccountById',
      getAdAccountList: 'plat.pinterest.getAdAccountList',
      createBoard: 'plat.pinterest.createBoard',
      getBoardList: 'plat.pinterest.getBoardList',
      getBoardById: 'plat.pinterest.getBoardById',
      delBoardById: 'plat.pinterest.delBoardById',
      createPin: 'plat.pinterest.createPin',
      getPinById: 'plat.pinterest.getPinById',
      getPinList: 'plat.pinterest.getPinList',
      delPinById: 'plat.pinterest.delPinById',
    },
    tiktok: {
      authUrl: 'plat.tiktok.authUrl',
      getAuthInfo: 'plat.tiktok.getAuthInfo',
      createAccountAndSetAccessToken:
        'plat.tiktok.createAccountAndSetAccessToken',
      refreshAccessToken: 'plat.tiktok.refreshAccessToken',
      revokeAccessToken: 'plat.tiktok.revokeAccessToken',
      getCreatorInfo: 'plat.tiktok.getCreatorInfo',
      initVideoPublish: 'plat.tiktok.initVideoPublish',
      initPhotoPublish: 'plat.tiktok.initPhotoPublish',
      getPublishStatus: 'plat.tiktok.getPublishStatus',
      uploadVideoFile: 'plat.tiktok.uploadVideoFile',
    },
    twitter: {
      authUrl: 'plat.twitter.authUrl',
      getAuthInfo: 'plat.twitter.getAuthInfo',
      createAccountAndSetAccessToken:
        'plat.twitter.createAccountAndSetAccessToken',
    },
  },
  publish: {
    pubRecord: {
      create: 'publish.pubRecord.create',
      del: 'publish.pubRecord.delete',
      info: 'publish.pubRecord.info',
      list: 'publish.pubRecord.list',
      updateStatus: 'publish.pubRecord.updateStatus',
    },
  },
  content: {
    admin: {
      material: {
        listByIds: 'content.admin.material.listByIds',
      },
    },
    material: {
      create: 'content.material.create',
      createTask: 'content.material.createTask',
      preview: 'content.material.preview',
      startTask: 'content.material.startTask',
      del: 'content.material.delete',
      delete: {
        minUseCount: 'content.material.delete.minUseCount',
      },
      updateInfo: 'content.material.updateInfo',
      info: 'content.material.info',
      list: 'content.material.list',
    },
    materialGroup: {
      create: 'content.materialGroup.create',
      del: 'content.materialGroup.delete',
      updateInfo: 'content.materialGroup.update',
      info: 'content.materialGroup.info',
      list: 'content.materialGroup.list',
    },
    media: {
      create: 'content.media.create',
      del: 'content.media.delete',
      info: 'content.media.info',
      list: 'content.media.list',
      addUseCount: 'content.media.addUseCount',
      addUseCountOfList: 'content.media.addUseCountOfList',
    },
    mediaGroup: {
      create: 'content.mediaGroup.create',
      del: 'content.mediaGroup.delete',
      update: 'content.mediaGroup.update',
      info: 'content.mediaGroup.info',
      list: 'content.mediaGroup.list',
    },
  },
  channel: {
    publishRecord: {
      userTask: 'channel.publishRecord.userTask',
    },
  },
  other: {
    feedback: {
      create: 'other.feedback.create',
    },
    appConfigs: {
      getInfo: 'other.appConfigs.getInfo',
      update: 'other.appConfigs.update',
      batchUpdate: 'other.appConfigs.batchUpdate',
      delete: 'other.appConfigs.delete',
      getList: 'other.appConfigs.getList',
    },
  },
  task: {
    task: {
      create: 'task.admin.task.create',
      update: 'task.admin.task.update',
      delete: 'task.admin.task.delete',
      updateStatus: 'task.admin.task.updateStatus',
      updateAutoDeleteMaterial: 'task.admin.task.updateAutoDeleteMaterial',
      list: 'task.admin.task.list',
      info: 'task.admin.task.info',
      publish: {
        accountList: 'task.admin.task.publish.accountList',
        userList: 'task.admin.task.publish.userList',
      },
      material: {
        delete: 'task.admin.task.material.delete',
        add: 'task.admin.task.material.add',
      },
    },
    taskOpportunity: {
      list: 'task.admin.taskOpportunity.list',
      del: 'task.admin.taskOpportunity.del',
    },
    userTask: {
      list: 'task.admin.userTask.list',
      info: 'task.admin.userTask.info',
      verifyApproved: 'task.admin.userTask.verifyApproved',
      verifyRejected: 'task.admin.userTask.verifyRejected',
      rollbackApproved: 'task.admin.userTask.rollbackApproved',
    },
    material: {
      create: 'task.admin.material.create',
      regenerate: 'task.admin.material.regenerate',
      get: 'task.admin.material.get',
      listByTaskId: 'task.admin.material.listByTaskId',
    },
    notification: {
      create: 'task.admin.notification.create',
      list: 'task.admin.notification.list',
      delete: 'task.admin.notification.delete',
    },
    matcher: {
      create: 'task.admin.matcher.create',
      get: 'task.admin.matcher.get',
      update: 'task.admin.matcher.update',
      delete: 'task.admin.matcher.delete',
      list: 'task.admin.matcher.list',
    },
    rule: {
      create: 'task.rule.create',
      get: 'task.rule.get',
      update: 'task.rule.update',
      delete: 'task.rule.delete',
      list: 'task.rule.list',
    },
    accountPortrait: {
      get: 'task.accountPortrait.get',
      list: 'task.accountPortrait.list',
    },
    userPortrait: {
      get: 'task.userPortrait.get',
      list: 'task.userPortrait.list',
    },
    taskPunish: {
      create: 'task.admin.taskPunish.create',
      info: 'task.admin.taskPunish.info',
      verifyApproved: 'task.admin.taskPunish.update',
      delete: 'task.admin.taskPunish.delete',
      list: 'task.admin.taskPunish.list',
    },
  },
  payment: {
    admin: {
      checkout: {
        list: 'payment.admin.checkout.list',
        refund: 'admin.payment.refund',
        subscription: 'admin.payment.subscription',
        unsubscribe: 'admin.payment.subscription',
      },
      withdraw: {
        info: 'payment.admin.withdraw.info',
        list: 'payment.admin.withdraw.list',
        release: 'payment.admin.withdraw.release',
      },
    },
  },
  ai: {
    chat: 'ai.chat.generations',
    chatModels: 'ai.chat.models',
    imageGenerations: 'ai.image.generations',
    imageEdits: 'ai.image.edits',
    imageVariations: 'ai.image.variations',
    videoGenerations: 'ai.video.generations',
    videoTaskQuery: 'ai.video.task.query',
    md2card: 'ai.md2card.generate',
    fireflycard: 'ai.fireflycard.generate',
    imageGenerationModels: 'ai.image.generation.models',
    imageEditModels: 'ai.image.edit.models',
    videoGenerationModels: 'ai.video.generation.models',
  },
  statistics: {
    account: {
      getAccountDataLatest: 'statistics.account.getAccountDataLatest',
      getAccountDataIncrease: 'statistics.account.getAccountDataIncrease',
      getAccountDataByParams: 'statistics.account.getAccountDataByParams',
      getAccountDataPeriod: 'statistics.account.getAccountDataPeriod',
      getChannelDataLatestByUids: 'statistics.account.getChannelDataLatestByUids',
      getChannelDataPeriodByUids: 'statistics.account.getChannelDataPeriodByUids',
    },
    channelPosts: {
      fetchChannelPosts: 'statistics.channel.posts',
    },
    task: {
      posts: {
        dataCube: 'statistics.task.posts.dataCube',
        periodDetail: 'statistics.task.posts.periodDetail',
      },
    },
    post: {
      detail: 'statistics.post.detail',
    },
  },
}
