interface Resources {
  'account': {
    title: '账户'
    describe: '账户页面'
    today: '今天'
    defaultSpace: 'defaultSpace'
    addPost: '添加帖子'
    calendarMode: '日历模式'
    listModeTab: '列表模式'
    newWork: '新建作品'
    allPlatforms: '所有平台'
    accountManager: '账号管理器'
    addAccount: '添加频道'
    mcpManagerTit: 'MCP 管理器'
    online: '在线'
    offline: '离线'
    checkLoginStatus: '登录状态检测'
    checkAllLoginStatus: '一键检测登录状态'
    nickname: '昵称'
    fansCount: '粉丝数'
    platform: '平台'
    loginStatus: '登录状态'
    accountStatus: '账号状态'
    normal: '正常'
    disabled: '禁用'
    unknownPlatform: '未知平台'
    unknownAccount: '未知账户'
    addAccountModal: {
      title: '账号添加'
      subtitle: '选择平台添加账号'
      currentSpace: '当前空间'
      pleaseChooseSpaceFirst: '请先选择空间'
      addTo: '添加到：'
    }
    facebookPages: {
      title: '选择Facebook页面'
      selectAll: '全选'
      cancel: '取消'
      confirm: '确认选择'
      loading: '加载中...'
      noPages: '暂无可用页面'
      fetchError: '获取页面列表失败'
      submitError: '页面选择失败'
      submitSuccess: '页面选择成功'
      selectAtLeastOne: '请至少选择一个页面'
      noPagesMessage: '您还没有创建任何Facebook页面'
      createPageTip: '点击上方链接创建页面，然后点击刷新按钮'
      createPageLink: '创建Facebook页面'
      refresh: '刷新'
    }
    listMode: {
      title: '发布计划列表'
      recordCount: '共 {{count}} 条发布计划'
      newWork: '新建作品'
      noRecords: '暂无发布计划'
      channels: '频道筛选'
      queue: '我的发布'
      sent: '发布历史'
      createdDaysAgo: '您于 {{days}} 天前创建'
      viewPost: '查看帖子'
      noSentPosts: '暂无已发布的帖子'
      selectAccountFirst: '请先选择一个账号'
      searchChannels: '搜索频道'
      selectAll: '全选'
      noChannelsFound: '未找到匹配的频道'
      selectChannel: '选择频道'
    }
    chooseSpace: '选择空间'
    pleaseChooseSpace: '请选择空间'
    accountAddedToSpace: '账号已添加到空间'
    noNewAccountDetected: '未检测到新账号，稍后可在账号管理器中手动调整空间'
    ipInfo: {
      loading: '获取IP信息中...'
      error: 'IP信息获取失败'
      tooltip: 'ASN: {{asn}}\n组织: {{org}}'
    }
    ipType: {
      direct: '直连'
      proxy: '代理'
    }
    createSpace: {
      title: '新建空间'
      button: '新建空间'
      name: '空间名'
      namePlaceholder: '请输入空间名称'
      cancel: '取消'
      save: '保存'
      success: '新建空间成功'
      failed: '新建空间失败'
      nameRequired: '请输入空间名称'
    }
    locationRestriction: {
      cnSpace: '当前空间为中国属地，仅显示国内平台'
      nonCnSpace: '当前空间为非中国属地，国内平台暂不可用'
    }
    userManageSidebar: {
      allAccounts: '全部账号'
      spaces: '空间'
      createSpace: '新建空间'
      spaceNamePlaceholder: '请输入空间名称'
      cannotOperateDefault: '不能操作默认列表'
      rename: '重命名'
      delete: '删除'
      confirmDelete: '提示'
      confirmDeleteContent: '请确认是否删除列表：'
      deleteSuccess: '删除成功'
      createSpaceTitle: '新建空间'
      renameSpaceTitle: '重命名空间'
      cancel: '取消'
      save: '保存'
      spaceName: '空间名'
    }
    userManageModal: {
      account: '账号'
      platform: '平台'
      space: '所属列表'
    }
    deleteAccount: '删除账户'
    messages: {
      ipLocationError: '获取IP地理位置信息失败'
      createSpaceFirst: '请先创建空间'
      deleteSuccess: '删除成功'
      facebookAuthFailed: 'Facebook授权失败'
      unsupportedPlatform: '未支持的平台类型'
      accountListRefreshed: '账号列表已刷新'
      refreshAccountListFailed: '刷新账号列表失败'
      authFailed: '授权失败'
      pleaseRetry: '请重试'
      platformNotSupported: '暂不支持 {{platform}} 平台的直接授权'
      sortSuccess: '排序成功'
      sortFailed: '排序失败'
    }
    rednote: '小红书'
    kwai: '快手'
    bilibili: '哔哩哔哩'
    wxgzh: '微信公众号'
    douyin: '抖音'
    wxsph: '微信视频号'
    deleteConfirm: {
      title: '删除提示'
      content: '是否删除以下 {{count}} 个账号？'
      cancel: '取消'
      confirm: '确认'
    }
    mobileOnlySupport: '移动端支持'
    xhsOfflineTip: '小红书账号已离线，请下载App进行操作'
    reauthConfirm: {
      title: '会话已过期'
      content: '您的 {{platformName}} 账号 "{{nickname}}"（位于 {{spaceName}}）会话已过期。是否重新登录？'
      loginAgain: '重新登录'
    }
    userManage: {
      selected: '已选择'
      accounts: '个账号'
      deleteAccount: '删除账号'
    }
    wechatBrowserTip: {
      clickCorner: '点击右上角的'
      dotsButton: '按钮'
      selectBrowser: '选择'
      openInBrowser: '在浏览器中打开'
    }
    mobileDownloadTip: {
      welcomeTitle: '欢迎使用 AitoEarn'
      description: '为了获得完整体验，请在设备上下载 App'
      downloadButton: '下载 App'
    }
    browserTip: {
      title: '请在浏览器中打开'
      description: '请点击右上角，通过浏览器打开'
      button: '我知道了'
    }
    platformNames: {
      douyin: '抖音'
      xiaohongshu: '小红书'
    }
    sidebar: {
      noAccounts: '暂无账户'
      noOnlineAccounts: '暂无在线账户'
      ipLocationTooltip: 'IP: {{ip}}\n位置: {{location}}'
      moveUp: '上移'
      moveDown: '下移'
    }
    mcpManager: {
      title: 'MCP 管理器'
      fetchKeysFailed: '获取MCP Key列表失败'
      createKeyFailed: '创建MCP Key失败'
      createAssociationFailed: '创建关联失败: {{account}}'
      createSuccess: 'MCP Key创建成功！'
      keyCopied: 'Key已复制到剪贴板'
      deleteSuccess: 'MCP Key已删除'
      deleteFailed: '删除MCP Key失败'
      createNewKey: '创建新Key'
      noKeys: '暂无MCP Key'
      noKeysDesc: '点击上方按钮创建您的第一个MCP Key'
      copy: '复制'
      detail: '详情'
      delete: '删除'
      available: '可用'
      unavailable: '不可用'
      createdAt: '创建时间: '
      associatedAccounts: '关联账户: '
      accountUnit: '个'
      pagination: '第 {{start}}-{{end}} 条，共 {{total}} 条'
      createModal: {
        title: '创建MCP Key'
        keyName: 'Key名称'
        keyNamePlaceholder: '请输入Key名称'
        keyNameRequired: '请输入Key名称'
        selectAccounts: '选择账户'
        selectAccountsPlaceholder: '请选择要关联的账户'
        selectAccountsRequired: '请选择至少一个账户'
        selectedCount: '已选择 {{count}} 个账户:'
        selectAccountsButton: '选择账户'
        create: '创建'
        cancel: '取消'
      }
    }
    mediaTypes: {
      video: '视频'
      image: '图片'
      article: '文章'
    }
    calendar: {
      showMore: '显示更多'
      hideMore: '隐藏更多'
    }
    proxy: {
      label: '代理地址'
      placeholder: '请输入代理地址'
      available: '代理地址可用'
      unavailable: '代理地址不可用'
      verify: '验证连接'
    }
  }
  'aiRank': {
    menu: {
      aiToolRanking: 'AI工具排行榜'
    }
    ranking: {
      title: 'AI工具排行榜'
      allRanking: '总榜'
      domesticRanking: '国内榜'
      foreignRanking: '国外榜'
      weekRanking: '周榜'
      monthRanking: '月榜'
      type: '类型'
      cycle: '周期'
    }
    table: {
      rank: '#'
      productName: '产品名'
      tags: '标签'
      monthlyVisits: '月访问量'
      monthlyDownloads: '月下载量'
      weeklyMentions: '周提及量'
      weeklyMentionsTooltip: '统计AI工具排行榜的周提及作品数'
      reputation: '声望值'
      reputationTooltip: '统计AI工具排行榜的提及作品、传播范围等多维度数据分析做出的综合评分'
      overallScore: '综合评分'
      overallScoreTooltip: '统计AI工具排行榜的用户使用情况等多维度数据分析做出的综合评分'
    }
    cycleSelect: {
      weekRanking: '周榜'
      monthRanking: '月榜'
    }
  }
  'cgmaterial': {
    header: {
      title: 'AI草稿箱'
      importContent: '导入发布内容'
      createGroup: '新建草稿箱组'
    }
    sidebar: {
      noGroups: '暂无草稿箱组'
      noGroupsDesc: '创建您的第一个草稿箱组开始整理素材'
      selectGroup: '请选择草稿箱组'
      selectGroupDesc: '从左侧选择一个草稿箱组来查看其中的素材'
      edit: '编辑'
      delete: '删除'
      deleteConfirm: '删除草稿组'
      deleteConfirmDesc: '确定要删除"{{name}}"吗？'
      deleteSuccess: '删除成功'
      deleteFailed: '删除失败'
      updateSuccess: '更新成功'
      updateFailed: '更新失败'
      noDesc: '暂无描述'
    }
    content: {
      noMaterials: '暂无草稿素材'
      noMaterialsDesc: '创建您的第一个素材或批量生成草稿'
      createMaterial: '创建素材'
      batchGenerate: '批量生成草稿'
      edit: '编辑'
      generating: '生成中'
      completed: '已生成'
    }
    createGroup: {
      title: '新建草稿箱组'
      name: '组名称'
      namePlaceholder: '请输入草稿箱组名称'
      type: '类型'
      typePlaceholder: '请选择草稿类型'
      imageText: '图文草稿'
      video: '视频草稿'
      desc: '描述'
      descPlaceholder: '请输入草稿箱组描述（可选）'
      createSuccess: '创建草稿箱组成功'
      createFailed: '创建草稿箱组失败'
      getGroupsFailed: '获取草稿箱组失败'
      getMaterialsFailed: '获取草稿素材失败'
    }
    createMaterial: {
      title: '创建素材'
      selectCoverGroup: '选择封面组（图片组）'
      selectCoverGroupDesc: '选择一个图片组作为封面来源'
      selectVideoGroup: '选择视频组'
      selectVideoGroupDesc: '选择一个视频组作为视频素材来源'
      selectCover: '选择封面（图片，单选）'
      selectVideo: '选择视频素材（单选）'
      reselectCoverGroup: '重新选择封面组'
      reselectVideoGroup: '重新选择视频组'
      coverMustBeImage: '封面必须是图片'
      imageGroupOnly: '图文组不能选择视频素材'
      videoGroupOnly: '视频组只能选择视频素材'
      selectMediaGroup: '请选择媒体组'
      selectCoverAndMaterials: '请完整选择封面和素材'
      selectCoverGroupRequired: '请选择封面组（图片组）'
      selectVideoGroupRequired: '请选择视频组'
      selectCoverRequired: '请选择封面（图片）'
      selectVideoRequired: '请选择视频素材'
      createSuccess: '创建素材成功'
      createFailed: '创建素材失败'
    }
    batchGenerate: {
      title: '批量生成草稿'
      model: '大模型'
      modelPlaceholder: '请选择大模型'
      prompt: '提示词'
      promptPlaceholder: '请输入提示词'
      titlePlaceholder: '请输入标题'
      descPlaceholder: '请输入简介'
      coverGroup: '封面组'
      coverGroupPlaceholder: '请选择封面组'
      mediaGroups: '素材组'
      mediaGroupsPlaceholder: '请选择素材组'
      num: '生成数量'
      location: '地理位置'
      preview: '预览'
      startTask: '开始任务'
      cancel: '取消'
      taskStarted: '批量生成任务已启动'
      generateFailed: '批量生成草稿失败'
      previewFailed: '获取预览失败'
      noPreview: '暂无预览内容'
    }
    previewModal: {
      title: '生成预览'
    }
    import: {
      title: '导入已有发布内容'
      selectAccount: '选择账户'
      publishContent: '{{nickname}} 的发布内容 (选择要导入的内容)'
      loadedCount: '共 {{total}} 条，已加载 {{loaded}} 条'
      loadMore: '加载更多 ({{count}} 条剩余)'
      importSelected: '导入选中内容'
      selectToImport: '请选择要导入的发布内容'
      selectGroupFirst: '请先选择草稿箱组'
      importSuccess: '成功导入 {{count}} 条内容到草稿箱'
      importFailed: '导入失败'
      getAccountsFailed: '获取账户列表失败'
      getPublishListFailed: '获取发布列表失败'
      checkProgress: '导入查询'
      importRecords: '导入记录详情'
      importStatus: '导入状态：'
      successCount: '成功 {{count}} 条'
      failedCount: '失败 {{count}} 条'
      runningCount: '进行中 {{count}} 条'
      pendingCount: '等待中 {{count}} 条'
      noRecords: '暂无导入记录'
      checkStatusFailed: '查询导入状态失败'
      accountId: '账户ID'
      userId: '用户ID'
      uid: 'UID'
      publishTime: '发布时间'
      mediaType: '媒体类型'
      image: '图片'
      video: '视频'
      article: '文章'
      desc: '描述'
      interactionData: '互动数据'
      views: '浏览'
      likes: '点赞'
      comments: '评论'
      shares: '分享'
      cover: '封面'
      close: '关闭'
      noTitle: '无标题'
      success: '成功'
      failed: '失败'
      running: '进行中'
      pending: '等待中'
      vipRequired: 'VIP专属功能'
      vipRequiredDesc: '导入发布内容功能仅限VIP会员使用，是否立即开通VIP会员？'
      upgradeNow: '立即开通'
      cancel: '取消'
      noValidRecords: '没有有效的发布内容可以导入'
      importFailedWithReason: '导入失败: {{reason}}'
      unknownError: '未知错误'
      status: {
        success: '成功'
        failed: '失败'
        running: '进行中'
        pending: '等待中'
      }
    }
    detail: {
      title: '素材详情'
      titleLabel: '标题：'
      descLabel: '简介：'
      typeLabel: '类型：'
      coverLabel: '封面：'
      materialsLabel: '素材内容：'
      statusLabel: '状态：'
      noMaterials: '暂无素材内容'
      materialImageAlt: '素材图片'
    }
    materialType: {
      imageText: '图文'
      video: '视频'
    }
    materialStatus: {
      generating: '生成中'
      completed: '已生成'
    }
    editGroup: {
      title: '编辑草稿箱组'
      namePlaceholder: '请输入新组名'
      enterName: '请输入新组名'
    }
    editMaterial: {
      title: '编辑素材'
      updateSuccess: '更新素材成功'
      updateFailed: '更新素材失败'
      selectMediaGroup: '选择媒体组'
      selectCover: '选择封面（单选）'
      selectMaterials: '选择素材（多选）'
    }
    fields: {
      title: '标题'
      description: '简介'
      location: '地理位置'
    }
    mediaGroupType: {
      img: '图片组'
      video: '视频组'
      mixed: '混合组'
    }
    selectCover: '选择封面（单选）'
    selectMaterials: '选择素材（多选）'
    validation: {
      enterTitle: '请输入标题'
    }
    title: '标题'
    description: '简介'
    location: '地理位置'
    mediaCount: '个资源'
    pleaseCompleteForm: '请完善表单信息'
  }
  'common': {
    profile: '个人中心'
    logout: '退出登录'
    unknownUser: '未知用户'
    docs: '帮助文档'
    login: '登录'
    support: '支持'
    notifications: '消息通知'
    noNotifications: '暂无消息'
    markAllAsRead: '全部标记为已读'
    markAsRead: '标记为已读'
    unreadCount: '未读消息'
    viewAll: '查看全部'
    actions: {
      cancel: '取消'
      confirm: '确认'
      selectAll: '全选'
      loading: '加载中...'
      noData: '暂无数据'
      noImage: '暂无图片'
      noDescription: '暂无描述'
      noContent: '暂无内容'
    }
    notificationTypes: {
      system: '系统通知'
      user: '用户通知'
      material: '素材通知'
      other: '其他通知'
    }
    header: {
      messages: '消息通知'
      income: '收入记录'
      wallet: '我的钱包'
      materialLibrary: '素材库'
      draftBox: '草稿箱'
    }
    tasks: '任务中心'
    signIn: {
      title: '每日签到得积分'
      myPoints: '我的积分'
      signIn: '签到'
      today: '今天'
      rules: '签到规则'
      rules1: '连续签到 1-7天, 每天1积分'
      rules2: '连续签到 8-21天, 每天2积分'
      rules3: '连续签到 22天以上, 每天3积分'
      signedIn: '已签到'
      notSignedIn: '未签到'
      signInSuccess: '签到成功'
      signInFailed: '签到失败'
      alreadySignedIn: '今日已签到'
      consecutiveDays: '连续签到天数'
      totalPoints: '总积分'
    }
    downloadApp: {
      title: '下载{{appName}}'
      operationInApp: '请在{{appName}}中操作添加'
      description: '为了更好的用户体验和功能完整性，该操作需要在 {{appName}} 中完成账号添加。请下载并安装 {{appName}} 后继续操作。'
      operationDescription: '请在Aitoearn App中操作{{platform}}频道账号<br/>为了更好的用户体验和完整性，请下载并安装Aitoearn App后继续操作。'
      scanQrCode: '扫描二维码下载'
      downloadLink: '下载链接：'
      copy: '复制'
      copySuccess: '复制成功'
      copyFailed: '复制失败，请手动复制'
      copied: '已复制'
      close: '关闭'
      downloadNow: '立即下载'
      tip: '💡 提示：安装完成后，请在App中登录您的账号，然后重新尝试相关操作'
    }
    websit: {
      termsOfService: {
        title: '用户协议'
        lastUpdated: '最后更新时间'
        content: {
          introduction: '欢迎使用我们的服务。在使用本服务前，请仔细阅读以下条款和条件。'
          acceptance: '1. 接受条款'
          acceptanceContent: '通过访问和使用本服务，您同意受本用户协议的约束。如果您不同意这些条款，请不要使用本服务。'
          serviceDescription: '2. 服务说明'
          serviceDescriptionContent: '本服务是一个AI内容创作平台，帮助用户生成和管理多媒体内容。'
          userResponsibilities: '3. 用户责任'
          userResponsibilitiesContent: '用户应确保其使用本服务的行为符合当地法律法规，不得用于非法目的。'
          privacy: '4. 隐私保护'
          privacyContent: '我们重视您的隐私，详细信息请参阅我们的隐私政策。'
          termination: '5. 服务终止'
          terminationContent: '我们保留在任何时候终止或暂停服务的权利。'
          contact: '6. 联系我们'
          contactContent: '如有任何问题，请通过邮件联系我们：support@example.com'
        }
      }
      privacyPolicy: {
        title: '隐私政策'
        lastUpdated: '最后更新时间'
        content: {
          introduction: '本隐私政策说明我们如何收集、使用和保护您的个人信息。'
          informationCollection: '1. 信息收集'
          informationCollectionContent: '我们收集您主动提供的信息以及您使用服务时自动收集的信息。'
          informationUse: '2. 信息使用'
          informationUseContent: '我们使用收集的信息来提供、维护和改进我们的服务。'
          informationSharing: '3. 信息共享'
          informationSharingContent: '我们不会向第三方出售、交易或转让您的个人信息。'
          dataSecurity: '4. 数据安全'
          dataSecurityContent: '我们采用适当的安全措施来保护您的个人信息。'
          userRights: '5. 用户权利'
          userRightsContent: '您有权访问、更正或删除您的个人信息。'
          contact: '6. 联系我们'
          contactContent: '如有隐私相关问题，请联系我们：privacy@example.com'
        }
      }
      dataDeletion: {
        title: '申请删除数据'
        subtitle: '如果您希望删除您的个人数据，请按照以下步骤操作'
        lastUpdated: '最后更新时间'
        prelaunchNote: '对于预发布用户：'
        prelaunchContent: '我们目前处于预发布阶段，如需删除数据，请直接联系我们的支持团队。'
        standardProcedure: '标准删除流程：'
        steps: [
          '登录您的账户并进入设置页面',
          '点击「数据管理」选项',
          '选择「删除我的数据」',
          '确认删除操作并等待处理完成',
        ]
        contactInfo: '联系方式：'
        contactEmail: '如需帮助，请发送邮件至：datadeletion@example.com'
        processingTime: '处理时间：'
        processingTimeContent: '数据删除请求通常在 7-14 个工作日内处理完成。'
        importantNote: '重要提示：'
        importantNoteContent: '数据删除后无法恢复，请谨慎操作。某些法律要求保留的数据可能无法删除。'
      }
    }
  }
  'dataStatistics': {
    title: '数据统计'
    description: '在这里查看和分析您的数据统计信息。'
    accountData: '账号数据'
    selectSpace: '选择空间'
    inputAccountName: '请输入账号名称'
    noAccount: '暂无账号'
    totalAccount: '累计账号数'
    online: '在线'
    offline: '离线'
    fansCount: '粉丝数'
    growthFansCount: '涨粉数'
    loginFailed: '登陆失败'
    relogin: '重新登录'
    dataDetails: '数据明细'
    timeRange: '时间范围：'
    yesterdayIncrease: '昨日新增'
    readCount: '播放数'
    commentCount: '评论数'
    likeCount: '点赞数'
    collectCount: '收藏数'
    forwardCount: '分享数'
  }
  'engagement': {
    title: '互动数据'
    columns: {
      postId: '帖子ID'
      platform: '平台'
      title: '标题'
      mediaType: '媒体类型'
      publishTime: '发布时间'
      viewCount: '浏览数'
      likeCount: '点赞数'
      commentCount: '评论数'
      shareCount: '分享数'
      clickCount: '点击数'
      impressionCount: '曝光数'
      favoriteCount: '收藏数'
      permaLink: '外链'
      open: '打开'
    }
    placeholders: {
      uid: '请输入账户UID'
    }
    actions: {
      search: '查询'
      reset: '重置'
    }
  }
  'home': {
    releaseBanner: {
      tag: 'Release v0.8.0'
      text: '通过插件和繁荣的市场构建和扩展AI工作流程。'
    }
    header: {
      logo: 'Aitoearn'
      nav: {
        home: '首页'
        marketplace: '市场'
        pricing: '价格'
        status: '状态'
        docs: '文档'
        blog: '博客'
        download: '下载'
      }
      getStarted: '立即开始'
    }
    hero: {
      stars: '105.2k'
      starsText: 'stars on'
      github: 'GitHub'
      title: '成为最好用的内容营销\nAI Agent'
      subtitle: '从今天起，使用AI轻松管理你的社交媒体。AITOEARN提供从灵感创意、内容制作，内容分发内容互动管理等一站式能力，让AI触手可及。'
      getStarted: '立即开始'
      useMobilePhone: '使用移动设备'
    }
    brandBar: {
      title: '支持的社交媒体平台'
    }
    buildSection: {
      badge: '功能1'
      title: 'Content Publishing — 一键发布 · 多平台触达'
      titleBlue: '从创意灵感到多平台分发，再到数据分析和商业化'
      features: {
        hotTopic: {
          title: '多平台分发'
          description: '支持全球最多主流社交平台（Douyin, Kwai, Wechat, Bilibili, Rednote, Facebook, Instagram, TikTok, LinkedIn, Threads, YouTube, Pinterest, X）。'
        }
        international: {
          title: '日历编排'
          description: '像操作日历一样规划内容，实现多平台协同发布。'
        }
      }
      carouselHint: '使用滚轮切换图片'
    }
    hotspotSection: {
      badge: '功能2'
      title: 'Content Hotspot — 爆款灵感引擎'
      titleBlue: '爆款案例库与趋势捕捉'
      features: {
        hotTopic: {
          title: '爆款案例库'
          description: '随时查看他人如何打造 10,000+ 点赞的内容。'
        }
        international: {
          title: '趋势捕捉'
          description: '快速发现流行趋势，降低创作焦虑。'
        }
      }
      carouselHint: '使用滚轮切换图片'
    }
    searchSection: {
      badge: '功能3'
      title: 'Content Search — 品牌与市场洞察'
      titleBlue: '品牌监控与内容搜索'
      features: {
        hotTopic: {
          title: '品牌监控'
          description: '实时追踪品牌相关讨论，第一时间响应。'
        }
        international: {
          title: '内容搜索'
          description: '找到目标帖子和话题，高效互动，精准拓展市场。'
        }
      }
      carouselHint: '使用滚轮切换图片'
    }
    commentsSection: {
      badge: '功能4'
      title: 'Comments Search — 精准用户挖掘'
      titleBlue: '智能评论搜索与精准转化'
      features: {
        hotTopic: {
          title: '智能评论搜索'
          description: '快速发现"求链接""怎么购买"等高转化信号。'
        }
        international: {
          title: '精准转化'
          description: '主动回复，提升流量变现效率。'
        }
      }
      carouselHint: '使用滚轮切换图片'
    }
    connectSection: {
      badge: '功能5'
      title: 'Content Engagement — 互动与增长引擎'
      titleBlue: '统一后台与主动运营'
      features: {
        creation: {
          title: '统一后台'
          description: '集中管理所有内容，互动零遗漏。'
        }
        distribution: {
          title: '主动运营'
          description: '参与热门话题，与潜在用户双向互动。把"被动内容运营"变成"主动流量经营"。'
        }
      }
      carouselHint: '使用滚轮切换图片'
    }
    upcomingSection: {
      badge: '即将上线'
      title: 'AI 驱动的全链路内容增长与变现平台'
      titleBlue: '即将上线功能，敬请期待'
      features: {
        smartImport: {
          title: '智能导入'
          description: '直接导入历史内容，快速编辑、二次分发。例如：小红书创作者可一键同步到 YouTube，让更多用户看到。'
        }
        analytics: {
          title: 'Content Analytics — 全景化数据视图'
          description: '多平台对比：一个平台不给流量，不代表所有平台不给。全链路监控：追踪内容表现，助力打造下一个百万博主。'
        }
        aiCreation: {
          title: 'AI Content Creation — 全流程 AI 助手'
          description: 'AI 文案生成：自动生成标题、描述，高效产出。AI 评论生成：主动出击，获取流量。图文卡片生成，全流程加速创作。支持主流 AI 视频模型和图片模型。'
        }
        marketplace: {
          title: 'Content Marketplace — 内容交易与变现'
          description: '创作者变现：在平台直接出售内容，让优质作品快速找到买家。品牌采购：企业可直接购买现成内容，节省时间与成本。让创作变成收益 —— Let\'s use AI to earn. Let\'s earn money together!'
        }
      }
    }
    downloadSection: {
      title: '随时随地开始创作'
      titleBlue: '移动端也能轻松管理'
      description: '借助 AI ToEarn 移动应用，您的创作不再局限于桌面端。我们还为您提供App移动应用，随时随地释放您的创造力，仅需一部手机即可！'
      qrCodeText: '扫描二维码下载'
      appStore: {
        text: 'Download on the'
        store: 'App Store'
      }
      googlePlay: {
        text: 'GET IT ON'
        store: 'Google Play'
      }
    }
    enterpriseSection: {
      badge: '企业级服务'
      title: '专业的AI自媒体解决方案'
      titleBlue: '助力企业营销成功'
      subtitle: '企业级AI营销转型不仅需要工具，更需要稳固的基础设施。AI ToEarn 提供可靠的平台，将AI内容创作能力分发到多个部门，实现无与伦比的营销效率。'
    }
    statsSection: {
      stats: {
        users: {
          number: '50K+'
          label: '用户'
        }
        platforms: {
          number: '15+'
          label: '社交平台'
        }
        countries: {
          number: '100+'
          label: '国家地区'
        }
        content: {
          number: '5M+'
          label: '内容发布'
        }
      }
      testimonial: {
        quote: '在内容营销竞争激烈的今天，快速验证和创作工具不仅有帮助，更是生存必需品。对于我们这样的营销公司来说，AI ToEarn 在这个AI前沿为我们提供了不可或缺的价值。'
        author: '李明'
        title: '某知名MCN机构 内容运营总监'
      }
      caseStudies: {
        timeSaved: {
          title: '预计每年节省创作时间'
          number: '50,000 小时'
        }
        aiAssistant: {
          title: 'AI营销助手：为500+企业客户提供跨平台内容分发服务'
        }
      }
    }
    communitySection: {
      badge: '社区生态'
      title: '加入我们的'
      titleBlue: '活跃创作者社区'
      subtitle: 'AI ToEarn 由全球AI内容创作者社区共同推动。加入我们，一起探索AI内容营销的无限边界。'
      buttons: {
        wechat: '微信群组'
        community: '创作者交流群'
      }
      wechatPopup: '扫码关注微信公众号'
      communityPopup: '扫码加入社区群'
      stats: {
        downloads: {
          number: '20万+'
          label: '下载量'
        }
        members: {
          number: '15K'
          label: '社区成员'
        }
        creators: {
          number: '500+'
          label: '活跃创作者'
        }
      }
    }
    footer: {
      resources: {
        title: '资源'
        links: {
          docs: '文档'
          blog: '博客'
          download: '下载'
          education: '教育'
          partner: '合作伙伴'
          support: '服务支持'
          roadmap: '产品线路图'
        }
      }
      company: {
        title: '公司'
        links: {
          talk: '联系我们'
          terms: '服务条款'
          privacy: '隐私政策'
          cookies: 'Cookie 设置'
          data: '数据删除引导'
          marketplace: '市场协议'
          brand: '品牌指南'
        }
      }
      description: 'AI ToEarn 自媒体运营平台一站式解决方案，从灵感创意到内容制作，从内容分发到内容互动管理'
      social: {
        github: 'GitHub'
        discord: 'Discord'
        youtube: 'YouTube'
        linkedin: 'LinkedIn'
        twitter: 'Twitter'
      }
      bigText: 'Let\'s Use AI To'
      copyright: '© 2025 AITOEARN, Corp.'
      tagline: ''
      dataDeletion: {
        title: 'Data Deletion Instructions'
        prelaunch: 'Our application is currently in pre-launch phase and does not store real user data. If you have interacted with our test systems, contact us for data removal.'
        standardTitle: 'Standard Procedure (Post-Launch):'
        standardSteps: [
          'Log in to your AiToEarn account',
          'Navigate to Settings > Privacy',
          'Click "Request Account Deletion"',
          'Confirmation will be sent to your registered email',
        ]
        contactTitle: 'Contact for Assistance:'
        contactEmail: 'Email: metat@aitoearning.com (Pre-launch inquiries only)'
      }
    }
  }
  'hot-content': {
    all: '全部'
    loading: '加载中...'
    noData: '暂无数据'
    rank: '排名'
    cover: '封面'
    title: '标题'
    author: '作者'
    category: '分类'
    likes: '点赞'
    shares: '分享'
    comments: '评论数'
    collections: '收藏数'
    publishTime: '发布于'
    fans: '粉丝数'
    viewMore: '查看更多'
    timeRange: '时间范围'
    filter: '筛选'
    hotTopics: '热门专题'
    viralTitles: '爆款标题'
    topics: '专题'
    engagement: '互动量'
    rising: '热'
    noHotTopics: '暂无热点数据'
    noViralTitles: '暂无爆款标题数据'
    noTopicData: '暂无专题数据'
    total: '总'
    items: '条'
    video: '视频'
    noImage: '暂无图片'
    platform: '平台'
    hotEvents: '热点事件'
    hotContent: '热点内容'
    noTitle: '暂无标题'
    baseInfo: '基本信息'
    views: '播放数'
    recommend: '推荐数'
    watch: '在看数'
    dailyRank: '日榜'
    updateFrequency: '更新时间'
    statEndTime: '统计数据截止'
    daily: '按日'
    sortRule: '排序规则'
    sortRuleDesc: '统计当日点赞量前500名的作品推荐'
    dataDescription: '数据说明'
    expand: '展开'
    collapse: '收起'
    hotValue: '热度值'
    hotTrend: '热度趋势'
    shortDrama: '短剧'
    cultureTourism: '文旅'
    contentOverseas: '内容出海'
    hot: '热点'
    last3days: '近3天'
    last7days: '近7天'
    last15days: '近15天'
    last30days: '近30天'
    backToAll: '返回全部'
    last90days: '近90天'
  }
  'imageEditor': {
    'Load': '加载本地'
    'Download': '下载当前'
    'Custom': '自定义'
    'Square': '正方形'
    'Apply': '应用'
    'Cancel': '取消'
    'Free': '自由设定'
    'Straight': '直线'
    'Color': '颜色'
    'Range': '粗细'
    'Grayscale': '灰度'
    'Invert': '旋转'
    'Sepia': '深褐色'
    'Sepia2': '深褐色2'
    'Blur': '模糊'
    'Sharpen': '锐化'
    'Emboss': '浮雕'
    'Remove White': '消除白色'
    'Distance': '边距'
    'Brightness': '亮度'
    'Noise': '降噪'
    'Pixelate': '像素化'
    'Color Filter': '颜色过滤'
    'Threshold': '阈值'
    'Tint': '色调'
    'Multiply': '复合'
    'Flip X': '镜像'
    'Flip Y': '翻转'
    'Reset': '重置'
    'Arrow-1': '箭头1'
    'Arrow-2': '箭头2'
    'Arrow-3': '箭头3'
    'Star-1': '星形1'
    'Star-2': '星形2'
    'Polygon': '多边形'
    'Location': '定位'
    'Heart': '心形'
    'Bubble': '气泡'
    'Custom icon': '自定义图标'
    'Load Mask Image': '加载水印'
    'Width': '宽'
    'Height': '高'
    'Lock Aspect Ratio': '保持尺寸比例'
    'Rectangle': '矩形'
    'Circle': '圆形'
    'Triangle': '三角形'
    'Fill': '填充'
    'Stroke': '画笔'
    'Bold': '加粗'
    'Italic': '斜体'
    'Underline': '下划线'
    'Left': '居左'
    'Center': '居中'
    'Right': '居右'
    'Text size': '字体大小'
    'Zoom In': '放大'
    'Zoom Out': '缩小'
    'ZoomIn': '放大'
    'ZoomOut': '缩小'
    'Hand': '拖动'
    'Resize': '尺寸'
    'Crop': '裁剪'
    'Flip': '翻转'
    'Rotate': '旋转'
    'Draw': '画笔'
    'Shape': '形状'
    'Icon': '图标'
    'Text': '文字'
    'Mask': '水印'
    'Filter': '滤镜'
    'History': '历史动作'
    'Undo': '撤退'
    'Redo': '重做'
    'Delete': '去除'
    'DeleteAll': '全部去除'
    'Blend': '混合'
    'imageEditing': '图像编辑'
  }
  'income': {
    title: '我的收入'
    subtitle: '管理您的收入记录和提现申请'
    currentBalance: '当前余额'
    incomeRecords: '收入记录'
    withdrawRecords: '提现记录'
    incomeId: '收入ID'
    amount: '金额'
    type: '类型'
    description: '描述'
    createTime: '创建时间'
    actions: '操作'
    applyWithdraw: '申请提现'
    withdrawId: '提现ID'
    status: '状态'
    updateTime: '更新时间'
    confirmWithdraw: '确认提现申请'
    cancel: '取消'
    confirm: '确认提现'
    withdrawAmount: '提现金额'
    incomeType: '收入类型'
    withdrawWarning: '⚠️ 提现申请提交后，我们将在1-3个工作日内处理您的申请。'
    withdrawWarning2: '请确保您的账户信息正确，提现成功后金额将转入您的指定账户。'
    incomeTypes: {
      task: '任务收入'
      task_back: '任务回退'
      reward_back: '奖励回退'
      task_withdraw: '任务提现'
    }
    withdrawStatus: {
      wait: '等待处理'
      success: '提现成功'
      fail: '提现失败'
      task_withdraw: '任务提现'
    }
    messages: {
      getIncomeRecordsFailed: '获取收入记录失败'
      getWithdrawRecordsFailed: '获取提现记录失败'
      withdrawSubmitted: '提现申请提交成功'
      withdrawFailed: '提现申请提交失败'
      pleaseLoginFirst: '请先登录'
      noIncomeRecords: '暂无收入记录'
      noWithdrawRecords: '暂无提现记录'
      loading: '加载中...'
      totalRecords: '共 {{total}} 条记录'
    }
    myWallet: '我的钱包'
  }
  'interactive': {
    title: '互动管理'
    messages: {
      pleaseLoginFirst: '请先登录'
      commentSuccess: '评论成功'
      commentFailed: '评论失败，请重试'
      replySuccess: '回复成功'
      replyFailed: '回复失败，请重试'
      aiReplyTaskCreated: 'AI回复任务已创建'
      aiReplyTaskFailed: 'AI回复创建失败'
    }
    ui: {
      selectChannel: '请在左侧选择需要互动的频道'
      selectChannelDesc: '选择一个账号后，将自动加载该频道的最新作品与评论互动功能。'
      loadMore: '加载更多'
      noMorePosts: '没有更多作品'
      loading: '加载中...'
      sending: '发送中...'
      send: '发送'
      reply: '回复'
      expandReplies: '展开回复'
      collapseReplies: '收起回复'
      loadMoreReplies: '加载更多回复'
      loadMoreComments: '加载更多评论'
      commentPlaceholder: '输入评论...'
      replyPlaceholder: '回复@'
      noImage: '无图片'
      videoPreview: '视频预览'
      aiReply: 'AI回复'
      aiReplyModalTitle: 'AI智能回复'
      selectAiModel: '选择AI模型：'
      aiModelPlaceholder: '请选择AI模型'
      replyPrompt: '回复提示词：'
      promptPlaceholder: '请输入AI回复的提示词，例如：请帮我生成一个友好、专业的回复'
      cancel: '取消'
      creating: '创建中...'
      createAiReplyTask: '创建AI回复任务'
    }
    stats: {
      likes: '点赞'
      comments: '评论'
      views: '浏览'
      shares: '分享'
      clicks: '点击'
      impressions: '曝光'
      favorites: '收藏'
    }
    mediaTypes: {
      video: '视频'
      image: '图片'
      article: '文章'
    }
  }
  'login': {
    welcomeBack: '哎呦赚'
    emailPlaceholder: '请输入注册邮箱'
    passwordPlaceholder: '密码'
    login: '登录/注册'
    or: '或'
    forgotPassword: '忘记密码？'
    completeRegistration: '完成注册'
    emailCode: '邮箱验证码'
    emailCodeRequired: '请输入邮箱验证码'
    emailCodeLength: '验证码长度为6位'
    enterEmailCode: '请输入邮箱验证码'
    setPassword: '设置密码'
    passwordRequired: '请输入密码'
    passwordMinLength: '密码长度不能小于6位'
    enterPassword: '请输入密码'
    inviteCode: '邀请码（选填）'
    enterInviteCode: '请输入邀请码'
    waitingForActivation: '等待激活中...'
    registering: '注册中...'
    loginSuccess: '登录成功'
    loginFailed: '登录失败'
    loginError: '登录失败，请稍后重试'
    activationEmailSent: '激活链接已发送至邮箱，请查收并点击激活'
    registerSuccess: '注册成功，已自动登录'
    checkStatusError: '检查注册状态失败'
    registerError: '注册失败，请稍后重试'
    googleLoginFailed: 'Google 登录失败'
    resetPassword: '重置密码'
    emailLabel: '邮箱'
    emailRequired: '请输入邮箱'
    emailInvalid: '请输入有效的邮箱地址'
    sendResetLink: '发送重置链接'
    newPassword: '新密码'
    newPasswordRequired: '请输入新密码'
    newPasswordMinLength: '密码长度不能小于6个字符'
    newPasswordPlaceholder: '请输入新密码'
    confirmPassword: '确认密码'
    confirmPasswordRequired: '请确认密码'
    confirmPasswordMismatch: '两次输入的密码不一致'
    confirmPasswordPlaceholder: '请确认密码'
    confirmReset: '确认重置'
    waitingForEmailConfirmation: '等待邮件确认中...'
    sendFailed: '发送失败'
    resetFailed: '重置失败'
    invalidResetCode: '无效的重置码'
    resetSuccess: '密码重置成功'
    clickEmailLinkToReset: '请点击邮件中的重置链接完成密码重置'
    backToLogin: '返回登录'
    verificationCode: '验证码'
    verificationCodeRequired: '请输入验证码'
    verificationCodePlaceholder: '请输入邮箱中的验证码'
    resetEmailSent: '重置邮件已发送，请查收'
    sendEmailFailed: '发送邮件失败'
    registerAccount: '注册账号'
    register: '注册'
    alreadyHaveAccount: '已有账号？去登录'
    passwordMismatch: '两次输入的密码不一致'
  }
  'material': {
    mediaManagement: {
      title: '媒体资源管理'
      createGroup: '创建媒体资源组'
      editGroup: '编辑媒体资源组'
      aiVideoGenerate: 'AI视频生成'
      groupName: '资源组名称'
      groupNamePlaceholder: '请输入资源组名称'
      description: '描述'
      descriptionPlaceholder: '请输入描述（可选）'
      type: '类型'
      video: '视频'
      image: '图片'
      create: '创建'
      save: '保存'
      cancel: '取消'
      delete: '删除'
      edit: '编辑'
      deleteConfirm: '确定要删除这个媒体资源组吗？'
      createSuccess: '创建媒体资源组成功'
      createFailed: '创建媒体资源组失败'
      updateSuccess: '更新媒体资源组成功'
      updateFailed: '更新媒体资源组失败'
      deleteSuccess: '删除媒体资源组成功'
      deleteFailed: '删除媒体资源组失败'
      getListFailed: '获取媒体资源组列表失败'
      noGroups: '暂无媒体资源组'
      noGroupsDesc: '创建您的第一个媒体资源组，开始管理您的素材'
      createNow: '立即创建'
      resources: '个资源'
      noDescription: '暂无描述'
    }
    aiGenerate: {
      title: 'AI生成'
      backToAlbum: '返回相册'
      textToImage: '文生图'
      imageToImage: '图生图'
      fireflyCard: 'Firefly卡片'
      videoGeneration: '视频生成'
      prompt: '提示词'
      promptPlaceholder: '请输入提示词'
      width: '宽度'
      height: '高度'
      generate: '生成'
      generating: '生成中...'
      content: '内容'
      contentPlaceholder: '请输入内容'
      titlePlaceholder: '请输入标题'
      template: '模板'
      uploadToMediaGroup: '上传到媒体组'
      selectMediaGroup: '选择媒体组'
      selectMediaGroupPlaceholder: '请选择媒体组'
      upload: '上传'
      uploading: '上传中...'
      uploadSuccess: '上传成功'
      uploadFailed: '上传失败'
      getMediaGroupListFailed: '获取媒体组列表失败'
      pleaseEnterPrompt: '请输入提示词'
      pleaseSelectMediaGroup: '请选择媒体组'
      pleaseEnterContent: '请输入内容'
      pleaseEnterTitle: '请输入标题'
      selectSize: '选择尺寸'
      generateCount: '生成数量'
      imageQuality: '图片质量'
      imageStyle: '图片风格'
      selectModel: '选择模型'
      standard: '标准'
      hd: '高清'
      vivid: '生动'
      natural: '自然'
      goldCardTemplate: '金卡模板'
      memoTemplate: '备忘录模板'
      simpleTemplate: '简约模板'
      blackSunTemplate: '黑日模板'
      templateE: '模板 E'
      writingTemplate: '写作模板'
      codeTemplate: '代码模板'
      templateD: '模板 D'
      videoPromptPlaceholder: '请输入视频描述'
      videoDuration: '视频时长'
      videoSize: '视频尺寸'
      videoMode: '生成模式'
      uploadImage: '上传图片'
      firstFrame: '首帧'
      tailFrame: '尾帧'
      imageUrlPlaceholder: '图片URL或base64'
      taskStatus: '任务状态'
      taskSubmitted: '任务已提交'
      taskProcessing: '任务处理中'
      taskCompleted: '任务完成'
      taskFailed: '任务失败'
      checkStatus: '检查状态'
      videoGenerationFailed: '视频生成失败'
      videoGenerationSuccess: '视频生成成功'
      pleaseEnterVideoPrompt: '请输入视频描述'
      pleaseSelectVideoModel: '请选择视频模型'
      videoUploadSuccess: '视频上传成功'
      videoUploadFailed: '视频上传失败'
      md2card: 'Markdown转卡片'
      markdownPlaceholder: '请输入Markdown内容'
      selectTheme: '选择主题'
      themeMode: '主题模式'
      lightMode: '浅色模式'
      darkMode: '深色模式'
      cardWidth: '卡片宽度'
      cardHeight: '卡片高度'
      splitMode: '分割模式'
      noSplit: '不分割'
      split: '分割'
      mdxMode: 'MDX模式'
      overHiddenMode: '溢出隐藏'
      generateCard: '生成卡片'
      cardGenerationFailed: '卡片生成失败'
      cardUploadSuccess: '卡片上传成功'
      cardUploadFailed: '卡片上传失败'
      pleaseEnterMarkdown: '请输入Markdown内容'
      imageGenerationFailed: '生成图片失败'
      fireflyCardGenerationFailed: '生成流光卡片失败'
      pleaseEnterContentAndTitle: '请输入内容和标题'
      taskSubmittedSuccess: '任务已提交'
      checkVideoTaskStatusFailed: '检查视频任务状态失败'
      pleaseEnterVideoDescription: '请输入视频描述'
      selectSizePlaceholder: '选择尺寸'
      generateCountPlaceholder: '生成数量'
      imageQualityPlaceholder: '图片质量'
      imageStylePlaceholder: '图片风格'
      selectModelPlaceholder: '选择模型'
      selectVideoModelPlaceholder: '选择视频模型'
      imageEditPromptPlaceholder: '请输入图片编辑提示词'
      uploadSourceImage: '上传源图片'
      uploadSourceImagePlaceholder: '请上传要编辑的图片'
      maxImages: '最多上传'
      imageEditFailed: '图片编辑失败'
      imageEditSuccess: '图片编辑成功'
      pleaseUploadSourceImage: '请上传源图片'
      imageEditTaskSubmitted: '图片编辑任务已提交'
      imageEditTaskProcessing: '图片编辑任务处理中'
      imageEditTaskCompleted: '图片编辑任务完成'
      imageEditTaskFailed: '图片编辑任务失败'
      advancedOptions: '高级选项'
      outputImageCount: '输出图像数量'
      low: '低'
      sourceImage: '源图片'
      deleteImage: '删除图片'
      clearAllImages: '清空所有图片'
      maxUploadReached: '已达到最大上传数量（{{count}}张）'
      maxUploadLimitReached: '已达到最大上传数量限制：{{count}}张图片'
      autoSelectImages: '只能上传{{count}}张图片，已自动选择前{{count}}张'
      uploadSuccessCount: '成功上传 {{count}} 张图片'
      autoRemoveExcessImages: '模型最多支持{{maxCount}}张图片，已自动移除{{removedCount}}张图片'
      imageEditCompleted: '图片编辑完成'
      imageGenerationCompleted: '图片生成完成'
      noDefaultMediaGroup: '未找到默认素材库组'
      pleaseUploadAtLeastOneImage: '请上传至少一张图片'
      addImage: '添加图片'
      image: '图片'
      videoGenerationHistory: '视频生成历史'
      refresh: '刷新'
      noHistoryRecords: '暂无历史记录'
      submitTime: '提交时间'
      completeTime: '完成时间'
      progress: '进度'
      failReason: '失败原因'
      completed: '已完成'
      failed: '失败'
      processing: '处理中'
      submitted: '已提交'
      examplePrompt1: '延时绽放'
      examplePrompt2: '绚丽花朵'
      examplePrompt3: '海底世界'
      examplePrompt4: '星空漫游'
      examplePrompt5: '赛博城市'
      textToVideo: '文本转视频'
      imageToVideo: '图文转视频'
      seconds: '秒'
      selectThemePlaceholder: '选择主题'
      themeModePlaceholder: '主题模式'
      cardWidthPlaceholder: '卡片宽度'
      cardHeightPlaceholder: '卡片高度'
      splitModePlaceholder: '分割模式'
      markdownToCard: 'Markdown转卡片'
      markdownCard: 'Markdown卡片'
      templateA: '默认'
      templateB: '透明'
      templateC: '金句'
      templateJin: '书摘'
      templateMemo: '便当'
      templateEasy: '边框'
      templateWrite: '手写'
      pleaseUploadFirstFrame: '请上传首帧图片'
      pleaseUploadTailFrame: '请上传尾帧图片'
      imageRequirements: '图片要求'
      aspectRatioRange: '宽高比范围'
      aspectRatioRangeValue: '(0.4, 2.5)'
      dimensionRange: '宽高长度范围'
      dimensionRangeValue: '(300px, 6000px)'
      imageSizeLimit: '图片大小限制'
      imageSizeLimitValue: '小于30MB'
      imageFormatSupport: '支持格式'
      imageFormatSupportValue: 'JPG, PNG, WEBP'
      estimatedCreditCost: '预计消耗积分'
      credits: '积分'
      getImageModelsFailed: '获取图片生成模型失败'
      getVideoModelsFailed: '获取视频生成模型失败'
    }
  }
  'notification': {
    title: '消息通知'
    detailTitle: '通知详情'
    markAllAsRead: '全部标记为已读'
    markAsRead: '标记为已读'
    delete: '删除'
    close: '关闭'
    noNotifications: '暂无通知'
    confirmDelete: '确定要删除这条通知吗？'
    confirm: '确定'
    cancel: '取消'
    deleteSuccess: '删除成功'
    deleteFailed: '删除失败'
    markSuccess: '标记成功'
    markFailed: '标记失败'
    markAllSuccess: '全部标记成功'
    getNotificationListFailed: '获取通知列表失败'
    getNotificationDetailFailed: '获取通知详情失败'
    createTime: '创建时间'
    readTime: '已读时间'
    taskDetail: '任务详情'
    acceptTask: '接受任务'
    noTaskDetails: '暂无任务详情'
    taskProcessing: '任务处理中...'
    acceptingTask: '正在接受任务...'
    publishingTask: '正在发布任务...'
    submittingTask: '正在提交任务...'
    taskCompleted: '任务完成'
    taskProcessFailed: '任务处理失败'
    acceptTaskFailed: '接受任务失败'
    publishTaskFailed: '发布任务失败'
    submitTaskFailed: '提交任务失败'
    getTaskDetailFailed: '获取任务详情失败'
    accountInfoFailed: '账号信息获取失败'
    appRequiredNotice: '⚠️ 注意：'
    appRequiredMessage: '发布账号({{platform}})的任务需要在移动端App中操作，请下载对应App后继续。'
    mediaPreview: '媒体预览'
    pageInfo: '第 {{start}}-{{end}} 条，共 {{total}} 条'
    notificationTypes: {
      system: '系统通知'
      user: '用户通知'
      material: '素材通知'
      task_reminder: '任务提醒'
      other: '其他通知'
    }
    taskStatus: {
      active: '进行中'
      inactive: '已结束'
    }
    taskInfo: {
      description: '描述'
      publisherAccount: '发布账号'
      reward: '奖励'
      taskType: '任务类型'
      platformTypes: '支持平台'
    }
    taskTypes: {
      video: '视频'
      article: '图文'
      article2: '纯文字'
    }
    platforms: {
      tiktok: 'TikTok'
      youtube: 'YouTube'
      twitter: 'Twitter'
      bilibili: '哔哩哔哩'
      KWAI: '快手'
      douyin: '抖音'
      xhs: '小红书'
      wxSph: '微信视频号'
      wxGzh: '微信公众号'
      facebook: 'Facebook'
      instagram: 'Instagram'
      threads: 'Threads'
      pinterest: 'Pinterest'
    }
    time: {
      justNow: '刚刚'
      minutesAgo: '{{minutes}}分钟前'
      hoursAgo: '{{hours}}小时前'
      daysAgo: '{{days}}天前'
    }
    accountSelect: {
      title: '选择发布账号'
      description: '描述'
      noAccounts: '没有符合条件的账号，请先添加账号'
      redirectingToAccounts: '正在跳转到账户界面，请添加符合条件的账号'
      accountId: '账号ID'
    }
  }
  'pinterest': {
    title: 'Pinterest 管理'
    tabs: {
      boards: '我的Board'
      pins: '我的Pin'
    }
    actions: {
      selectAccount: '选择账户'
      refresh: '刷新'
      createBoard: '创建Board'
      createPin: '创建Pin'
      search: '搜索...'
      view: '查看'
      edit: '编辑'
      delete: '删除'
      link: '链接'
      change: '更改'
    }
    stats: {
      followers: '关注者'
      boardCount: 'Board数量'
      pinCount: 'Pin数量'
      monthlyViews: '月观看量'
    }
    board: {
      createTitle: '创建新Board'
      name: 'Board名称'
      namePlaceholder: '输入Board名称'
      description: '描述'
      descriptionPlaceholder: '输入Board描述'
      privacy: '隐私设置'
      public: '公开'
      private: '私有'
      createButton: '创建Board'
      deleteConfirm: '确定删除此Board吗？'
      detailTitle: 'Board详情'
      createTime: '创建时间'
      noDescription: '暂无描述'
    }
    pin: {
      createTitle: '创建新Pin'
      selectBoard: '选择Board'
      selectBoardPlaceholder: '选择要发布到的Board'
      uploadImage: '上传图片'
      uploadImagePlaceholder: '点击上传图片到OSS'
      uploadHint: '支持JPG、PNG、GIF格式，最大10MB'
      uploading: '正在上传到OSS...'
      uploadSuccess: '✓ 上传成功'
      reupload: '重新上传'
      ossUrl: 'OSS地址'
      title: '标题'
      titlePlaceholder: '输入Pin标题'
      description: '描述'
      descriptionPlaceholder: '输入Pin描述'
      link: '链接'
      linkPlaceholder: '输入目标链接（可选）'
      altText: 'Alt文本'
      altTextPlaceholder: '输入图片Alt文本（可选）'
      dominantColor: '主色调'
      dominantColorTip: '选择Pin的主色调'
      createButton: '创建Pin'
      deleteConfirm: '确定删除此Pin吗？'
      detailTitle: 'Pin详情'
      pinId: 'Pin ID'
      boardId: 'Board ID'
      creativeType: '创作类型'
      boardOwner: 'Board拥有者'
      isOwner: '拥有者'
      isRemovable: '可移除'
      isStandard: '标准Pin'
      noDescription: '暂无描述'
      imageAlt: 'Pin图片'
    }
    badges: {
      pins: 'Pins'
      followers: '关注者'
      owner: '拥有者'
      yes: '是'
      no: '否'
      selected: '当前选择'
    }
    empty: {
      noBoards: '暂无Board'
      noPins: '暂无Pin'
    }
    pagination: {
      total: '第 {range} 条，共 {total} 条'
    }
    messages: {
      loadAccountsFailed: '加载账户列表失败'
      loadBoardsFailed: '加载Board列表失败'
      loadPinsFailed: '加载Pin列表失败'
      boardCreateSuccess: 'Board创建成功'
      boardCreateFailed: '创建Board失败'
      boardDeleteSuccess: 'Board删除成功'
      boardDeleteFailed: '删除Board失败'
      pinCreateSuccess: 'Pin创建成功'
      pinCreateFailed: '创建Pin失败'
      pinDeleteSuccess: 'Pin删除成功'
      pinDeleteFailed: '删除Pin失败'
      getBoardDetailFailed: '获取Board详情失败'
      getPinDetailFailed: '获取Pin详情失败'
      uploadImageFirst: '请先上传图片'
      selectImageFile: '请选择图片文件'
      imageSizeLimit: '图片大小不能超过10MB'
      imageUploadSuccess: '图片上传成功'
      imageUploadFailed: '图片上传失败，请重试'
      noAccountFound: '没有找到Pinterest账户'
    }
    validation: {
      boardNameRequired: '请输入Board名称'
      selectBoardRequired: '请选择Board'
      titleRequired: '请输入标题'
      descriptionRequired: '请输入描述'
    }
    confirm: {
      ok: '确定'
      cancel: '取消'
    }
  }
  'pricing': {
    title: '套餐与定价'
    subtitle: '选择最适合您需求的套餐，开始您的AI创作之旅'
    monthly: '月付'
    yearly: '年付'
    save25: '省25%'
    save50: '省50%'
    month: '月'
    credits: '积分'
    videos: '视频'
    images: '图片'
    flashSale50: '限时5折'
    mostPopular: '最受欢迎'
    plans: {
      free: {
        name: 'Free'
        credits: '最高60 积分'
        videos: '每月最高可生成60个视频'
        images: '每月最高可生成120张图片'
        button: '立即开始'
      }
      plus: {
        name: 'Plus'
        credits: '700积分'
        videos: '每月最高可生成700个视频'
        images: '每月最高可生成1400张图片'
        button: '立即购买'
      }
    }
    features: {
      textModeration: '文本内容安全审查'
      imageModeration: '图片内容安全审查'
      videoModeration: '视频内容安全审查'
      multiModel: '多模型一站式支持'
      textToVideo: '文字转视频'
      imageToVideo: '图像转视频'
      videoToVideo: '视频到视频'
      consistentCharacter: '一致的角色视频'
      aiAnimation: 'AI动画生成'
      aiImage: 'AI图像生成'
      voiceClone: '声音克隆'
      voiceSynthesis: '声音合成'
      fasterSpeed: '更快的生成速度'
      withWatermark: '含水印输出'
      noWatermark: '无水印输出'
      storage500M: '存储空间500M'
      storage5G: '存储空间5G'
    }
    faq: {
      title: '常见问题'
      paymentMethods: {
        question: '你们支持哪些支付方式？'
        answer: '我们支持多种支付方式，包括主要的信用卡（Visa、MasterCard、American Express）以及支付宝等。如果您在中国使用我们的服务，可以通过支付宝购买一次性服务。'
      }
      creditDeduction: {
        question: '图片和视频生成时，积分是如何扣除的？'
        answer: '我们的图片和视频生成定价与官方渠道保持一致。通常情况下，如果官方渠道有大额采购折扣，我们也会同步将这些优惠让利给您。'
        pricingTable: {
          title: '详细价格表'
          headers: {
            model: '模型'
            type: '类型'
            duration: '时长'
            resolution: '分辨率'
            notes: '备注'
            credits: '积分'
            price: '价格'
            channel: '渠道'
          }
          rows: [
            {
              model: 'gpt-5'
              type: '大模型'
              duration: ''
              resolution: ''
              notes: '大模型价格以官方价格为准'
              credits: '每百万tokens'
              price: '输入 9元，输出 72元'
              channel: 'yun'
            },
            {
              model: 'gpt-5-mini'
              type: '大模型'
              duration: ''
              resolution: ''
              notes: ''
              credits: ''
              price: '输入 1.8元，输出 14.4元'
              channel: 'yun'
            },
            {
              model: 'gpt-5-nano'
              type: '大模型'
              duration: ''
              resolution: ''
              notes: ''
              credits: ''
              price: '输入 0.36元，输出 2.88元'
              channel: 'yun'
            },
            {
              model: 'gemini-2.5-pro'
              type: '大模型'
              duration: ''
              resolution: '支持视频'
              notes: ''
              credits: ''
              price: '输入9元，输出 72元'
              channel: 'yun'
            },
            {
              model: 'chatgpt-4o-latest'
              type: '大模型'
              duration: ''
              resolution: ''
              notes: ''
              credits: ''
              price: '输入 36元，输出 108元'
              channel: 'yun'
            },
            {
              model: 'gemini-2.5-flash'
              type: '大模型'
              duration: ''
              resolution: '支持视频'
              notes: ''
              credits: ''
              price: '输入 2.16元，输出 18元'
              channel: 'yun'
            },
            {
              model: 'qwen-vl-max-latest'
              type: '大模型'
              duration: ''
              resolution: ''
              notes: ''
              credits: ''
              price: '输入1.6元，输出4元'
              channel: 'yun'
            },
            {
              model: 'gemini-2.5-flash-image'
              type: '图片生成'
              duration: ''
              resolution: ''
              notes: '又名nano banana，支持多图像输入'
              credits: '1'
              price: '0.27元'
              channel: 'yun'
            },
            {
              model: 'seedream-3.0'
              type: '图片生成'
              duration: ''
              resolution: ''
              notes: ''
              credits: '2.6'
              price: '0.26元'
              channel: '官方'
            },
            {
              model: 'seededit-3.0'
              type: '图片生成'
              duration: ''
              resolution: ''
              notes: '图片编辑，支持jpeg、png格式'
              credits: '3'
              price: '0.3元'
              channel: '官方'
            },
            {
              model: 'gpt-image-1'
              type: '图片生成'
              duration: ''
              resolution: '支持图片编辑'
              notes: ''
              credits: '促销'
              price: 'low $0.011-0.016，medium $0.042-0.063，high $0.167-0.25'
              channel: 'yun'
            },
            {
              model: 'FLUX.1 Kontext [max]'
              type: '图片生成'
              duration: ''
              resolution: '支持图片编辑'
              notes: ''
              credits: '1.5'
              price: '0.6元'
              channel: 'yun'
            },
            {
              model: 'FLUX.1 Kontext [pro]'
              type: '图片生成'
              duration: ''
              resolution: '支持图片编辑'
              notes: ''
              credits: '1'
              price: '0.3元'
              channel: 'yun'
            },
            {
              model: 'Flux 1.1 pro ultra'
              type: '图片生成'
              duration: ''
              resolution: ''
              notes: ''
              credits: '4.5'
              price: '0.45元'
              channel: '官方'
            },
            {
              model: 'Flux1.1 pro'
              type: '图片生成'
              duration: ''
              resolution: ''
              notes: ''
              credits: '3'
              price: '0.3元'
              channel: '官方'
            },
            {
              model: 'midjourney relax'
              type: '视频生成'
              duration: '5秒'
              resolution: ''
              notes: ''
              credits: '免费'
              price: ''
              channel: 'yun'
            },
            {
              model: 'midjourney fast/turbo'
              type: '视频生成'
              duration: '5秒'
              resolution: ''
              notes: ''
              credits: '4'
              price: ''
              channel: 'yun'
            },
            {
              model: 'kling1.5/1.6/2.1'
              type: '视频生成'
              duration: '5秒'
              resolution: '720p'
              notes: ''
              credits: '20'
              price: '2元'
              channel: 'yun'
            },
            {
              model: 'kling1.5/1.6/2.1'
              type: '视频生成'
              duration: '10秒'
              resolution: '720p'
              notes: ''
              credits: '40'
              price: '4元'
              channel: 'yun'
            },
            {
              model: 'kling1.5/1.6/2.1'
              duration: '5秒'
              resolution: '1080p'
              notes: ''
              credits: '35'
              price: '3.5元'
              channel: 'yun'
            },
            {
              model: 'kling1.5/1.6/2.1'
              type: '视频生成'
              duration: '10秒'
              resolution: '1080p'
              notes: ''
              credits: '70'
              price: '7元'
              channel: 'yun'
            },
            {
              model: 'kling2.1大师'
              type: '视频生成'
              duration: '5秒'
              resolution: '1080p'
              notes: ''
              credits: '100'
              price: '10元'
              channel: 'yun'
            },
            {
              model: 'kling2.1大师'
              type: '视频生成'
              duration: '10秒'
              resolution: '1080p'
              notes: ''
              credits: '200'
              price: '20元'
              channel: 'yun'
            },
            {
              model: 'wan2.2-plus'
              type: '视频生成'
              duration: '5秒'
              resolution: '480p'
              notes: ''
              credits: '70'
              price: '0.7元'
              channel: 'yun'
            },
            {
              model: 'wan2.2-plus'
              type: '视频生成'
              duration: '5秒'
              resolution: '1080p'
              notes: ''
              credits: '35'
              price: '3.5元'
              channel: 'yun'
            },
            {
              model: 'wan2.1-turbo(14b）'
              type: '视频生成'
              duration: '5秒'
              resolution: '720p'
              notes: '不要使用火山渠道'
              credits: '12'
              price: '1.2元'
              channel: 'yun'
            },
            {
              model: 'wan2.1-plus'
              type: '视频生成'
              duration: '5秒'
              resolution: '720p'
              notes: '支持首尾帧'
              credits: '35'
              price: '3.5元'
              channel: 'yun'
            },
            {
              model: 'wanx2.1-vace-plus'
              type: '视频生成'
              duration: '5秒'
              resolution: '720p'
              notes: '视频编辑'
              credits: '35'
              price: '3.5元'
              channel: 'yun'
            },
            {
              model: 'seedance-1.0-pro'
              type: '视频生成'
              duration: '5秒'
              resolution: '480p'
              notes: '支持10秒'
              credits: '7.2'
              price: '0.72元'
              channel: 'yun'
            },
            {
              model: 'seedance-1.0-pro'
              type: '视频生成'
              duration: '5秒'
              resolution: '720p'
              notes: '10秒价格翻倍'
              credits: '16.4'
              price: '1.64元'
              channel: 'yun'
            },
            {
              model: 'seedance-1.0-pro'
              type: '视频生成'
              duration: '5秒'
              resolution: '1080p'
              notes: ''
              credits: '36.7'
              price: '3.67元'
              channel: 'yun'
            },
            {
              model: 'seedance-1.0-lite'
              type: '视频生成'
              duration: '5秒'
              resolution: '480p'
              notes: '支持首尾帧'
              credits: '5'
              price: '0.5元'
              channel: 'yun'
            },
            {
              model: 'seedance-1.0-lite'
              type: '视频生成'
              duration: '5秒'
              resolution: '720p'
              notes: '支持10秒'
              credits: '11'
              price: '1.1元'
              channel: 'yun'
            },
            {
              model: 'seedance-1.0-lite'
              type: '视频生成'
              duration: '5秒'
              resolution: '1080p'
              notes: '10秒价格翻倍'
              credits: '25'
              price: '2.5元'
              channel: 'yun'
            },
          ]
        }
      }
      creditExpiry: {
        question: '我的积分会过期吗？'
        answer: '我们的积分过期机制非常宽松。积分自获取之日起 12 个自然月后才会过期，您有充足的时间使用。'
      }
      moreCredits: {
        question: '如果我需要更多积分怎么办？'
        answer: '您可以通过每天发布内容来获取免费积分。同时，也可以通过开通会员或直接购买积分的方式获得更多积分。'
      }
      checkCredits: {
        question: '如何查看我的积分情况？'
        answer: '点击您的积分余额，即可查看积分的变更明细。'
      }
      hiddenFees: {
        question: '是否存在隐藏费用？'
        answer: '没有。您所看到的价格就是您最终支付的价格，不会有任何额外的隐性收费。'
      }
      refundPolicy: {
        question: '有退款政策吗？'
        answer: '我们提供7天无理由退款保证。如果您对服务不满意，可以在购买后7天内申请全额退款。'
      }
    }
  }
  'profile': {
    personalInfo: '个人信息'
    orderManagement: '订单管理'
    myOrders: '购买记录'
    mySubscriptions: '我的订阅'
    plusMember: 'PLUS会员'
    vipUserGreeting: '尊敬的VIP用户，您已解锁全部会员权益'
    vipDescription: '开通会员解锁全部功能，立享8种权益'
    activateNow: '立即开通'
    modifyUsername: '修改用户名'
    logout: '退出登录'
    userId: '用户ID'
    username: '用户名'
    email: '邮箱'
    accountStatus: '账号状态'
    normal: '正常'
    disabled: '禁用'
    memberType: '会员类型'
    memberExpireTime: '会员到期时间'
    nonMember: '非会员'
    monthlyMember: '月度会员'
    yearlyMember: '年度会员'
    unknown: '未知'
    upgradeCallToAction: '开通PLUS会员，体验更多高级功能！'
    activatePlusMember: '立即开通PLUS会员'
    orderId: '订单ID'
    packageType: '套餐类型'
    amount: '金额'
    status: '状态'
    createTime: '创建时间'
    expireTime: '过期时间'
    actions: '操作'
    viewDetails: '查看详情'
    goToPay: '去支付'
    subscriptionId: '订阅ID'
    cancelSubscription: '退订'
    cancelSubscriptionConfirm: '确定要退订吗？退订后将无法享受会员权益。'
    confirm: '确定'
    cancel: '取消'
    orderDetails: '订单详情'
    close: '关闭'
    goToPayment: '前往支付'
    internalId: '内部ID'
    subscriptionMode: '订阅模式'
    paymentMethod: '支付方式'
    refundedAmount: '已退款金额'
    paymentIntent: 'Payment Intent'
    paymentLink: '支付链接'
    openPaymentPage: '打开支付页面'
    totalRecords: '共 {total} 条记录'
    loading: '加载中...'
    noOrderRecords: '暂无订单记录'
    noSubscriptionRecords: '暂无订阅记录'
    pleaseLoginFirst: '请先登录'
    logoutSuccess: '退出登录成功'
    updateSuccess: '更新成功'
    updateFailed: '更新失败'
    getUserInfoFailed: '获取用户信息失败'
    getOrderListFailed: '获取订单列表失败'
    getSubscriptionListFailed: '获取订阅列表失败'
    refundSubmitted: '退款申请已提交'
    refundFailed: '退款失败'
    unsubscribeSuccess: '退订成功'
    unsubscribeFailed: '退订失败'
    getOrderDetailFailed: '获取订单详情失败'
    pleaseEnterUsername: '请输入用户名'
    usernameLengthMin: '用户名长度不能小于2个字符'
    usernameLengthMax: '用户名长度不能超过20个字符'
    confirmModify: '确认修改'
    monthlySubscription: '月度订阅'
    yearlySubscription: '年度订阅'
    oneTimeMonthly: '一次性月度'
    oneTimeYearly: '一次性年度'
    paymentSuccess: '已完成'
    waitingForPayment: '待支付'
    refundSuccess: '退款成功'
    orderCancelled: '订单取消'
    subscriptionSuccess: '订阅成功'
    subscriptionCancelled: '已取消'
    subscription: '订阅'
    quantity: '数量'
    orderExpired: '已过期'
    unknownStatus: '状态'
    cancelTime: '取消时间'
    trialEndTime: '试用结束时间'
    willCancelAtPeriodEnd: '将于期末取消'
    subscriptionPastDue: '逾期'
    copySuccess: '已复制'
    resumeSubscription: '恢复订阅'
    resumeSuccess: '恢复成功'
    vipBenefits: {
      exclusiveBadge: '专属标识'
      advancedFeatures: '高级功能'
      memberGift: '会员礼包'
      prioritySupport: '优先支持'
      discount: '优惠折扣'
      unlimitedTime: '无限时长'
      fastExperience: '极速体验'
      morePrivileges: '更多特权'
    }
    points: {
      title: '积分记录'
      myPoints: '我的积分'
      pointsDescription: '查看您的积分变动记录和使用情况'
      pointsChange: '积分变动'
      balance: '余额'
      changeType: '变动类型'
      description: '描述'
      time: '时间'
      earn: '获得'
      spend: '消费'
      refund: '退还'
      expire: '过期'
      aiService: 'AI服务'
      userRegister: '用户注册'
      publish: '发布作品'
      point: '积分交易'
      noPointsRecords: '暂无积分记录'
      totalRecords: '共 {{total}} 条记录'
    }
    pointsPurchase: {
      title: '购买积分'
      currentPoints: '当前积分'
      selectAmount: '选择购买数量'
      description: '每1000积分售价15美元，滑动选择购买数量'
      purchasePoints: '购买积分'
      totalPrice: '总价'
      buyNow: '立即购买'
      paying: '支付中...'
      paymentTip: '支付完成后，请点击下方按钮确认支付状态'
      confirmPayment: '我已支付'
      purchaseSuccess: '积分购买成功！'
      paymentPending: '订单尚未支付成功，请稍后再试'
      orderRefunded: '订单已退款'
      orderCancelled: '订单已取消'
      orderUnknown: '订单状态未知，请稍后再试'
      queryFailed: '查询订单状态失败，请重试'
      createOrderFailed: '创建支付订单失败，请重试'
      redirectingToPayment: '正在跳转到支付页面...'
      publish: '发布'
      publishDesc: '发布内容获得积分奖励'
      vip: '开通会员'
      vipDesc: '会员专享积分福利'
      buyPoints: '购买积分'
      buyPointsDesc: '直接充值获得积分'
      getPointsMethods: '获取积分的方法：'
    }
    freeTrial: {
      title: '🎉 免费会员体验'
      congratulations: '恭喜您获得3天免费会员体验！'
      description: '作为新用户，您可以享受3天的免费会员权益，体验所有高级功能，包括：'
      unlimitedAI: '✓ 无限制AI生成'
      priorityProcessing: '✓ 优先处理'
      advancedModels: '✓ 高级模型'
      dedicatedSupport: '✓ 专属客服'
      noAds: '✓ 无广告体验'
      morePrivileges: '✓ 更多特权'
      completelyFree: '🎁 完全免费，无需支付任何费用'
      claimNow: '立即领取'
      later: '稍后再说'
    }
    vipHonorText: '您是尊贵的VIP用户'
    inviteCode: '邀请码'
    edit: '编辑'
    copy: '复制'
    cancelAccount: '注销账户'
    cancelAccountWarning: '注销账户是不可逆的操作，一旦注销，您的所有数据将被永久删除，包括：'
    cancelAccountDataList: '个人资料和设置,所有发布的内容,积分和会员权益,订单和支付记录'
    cancelAccountCaution: '请谨慎操作！'
    cancelAccountSecurity: '为了您的账户安全，请先获取验证码进行身份验证。'
    verificationCode: '验证码'
    pleaseEnterVerificationCode: '请输入验证码'
    getVerificationCode: '获取验证码'
    resendAfter: 's后重发'
    confirmCancel: '确认注销'
    stats: {
      totalEarned: '累计赚钱'
      balance: '当前余额'
      points: '可用积分'
      coupons: '优惠券'
      currencyYuan: '元'
    }
    deleteAccount: {
      title: '删除你的账户'
      desc: '删除账户后，你将无法继续使用 Aitoearn 服务，我们也会永久删除你的个人数据。'
      apply: '申请注销'
    }
    messages: {
      getPointsRecordsFailed: '获取积分记录失败'
      verificationCodeSent: '验证码已发送'
      getVerificationCodeFailed: '获取验证码失败'
      accountCancelledSuccess: '账户注销成功'
      priceId: '价格ID'
    }
    memberTypes: {
      oneTime: '一次性'
      trial: '试用'
    }
  }
  'publish': {
    title: '发布作品'
    confirmClose: {
      title: '确认关闭'
      content: '关闭后，已填写的内容将丢失，是否确认关闭？'
    }
    buttons: {
      customizePerAccount: '自定义每个账户'
      cancelPublish: '取消发布'
      schedulePublish: '定时发布'
      publishNow: '立即发布'
      copyLink: '复制链接'
      delete: '删除'
    }
    tips: {
      workSaved: '你的工作被保存了，请选择账号，继续发布'
      pcNotSupported: 'Web不支持该平台，请下载App进行发布'
      accountOffline: '该账号已离线，无法发布'
      tiktokForbidden: '该平台暂不支持发布'
      xhsOffline: '小红书账号已离线，请下载App进行操作'
      selectAccount: '请选择要发布的账户'
    }
    status: {
      publishFailed: '发布失败'
      publishing: '发布中'
      publishSuccess: '发布成功'
      waitingPublish: '等待发布'
      unknown: '未知状态'
    }
    creationInfo: '您于 {{date}} 创建了此内容'
    form: {
      title: '标题'
      titlePlaceholder: '请输入标题'
      partition: '分区'
      partitionPlaceholder: '请选择分区'
      type: '类型'
      original: '原创'
      reprint: '转载'
      source: '转载来源'
      sourcePlaceholder: '转载视频请注明来源、时间、地点(例：转自https://www.xxxx.com/yyyy)'
      page: '页面'
      pagePlaceholder: '请选择页面'
      privacyStatus: '隐私状态'
      selectPrivacyStatus: '请选择隐私状态'
      public: '公开'
      unlisted: '不公开'
      private: '私人'
      region: '国区'
      regionPlaceholder: '请选择国区'
      license: '许可证'
      licensePlaceholder: '请选择许可证'
      standardYouTubeLicense: '标准 YouTube 许可证'
      creativeCommonsLicense: '知识共享许可证'
      category: '视频分类'
      categoryPlaceholder: '请选择视频分类'
      categoryPlaceholderDisabled: '请先选择国区'
      board: 'Board'
      boardPlaceholder: '请选择Board'
      location: '位置'
      searchLocation: '搜索位置'
      selectLocation: '请选择位置'
      description: '描述'
      descriptionPlaceholder: '开始写'
    }
    writingAssistant: '写作助手'
    upload: {
      finishingUp: '正在完成...'
      uploadImageOrVideo: '上传图片或视频'
      uploadImage: '请上传图片'
      uploadVideo: '请上传视频'
      dragAndSelect: '拖放 & 选择图片或视频'
      selectFile: '选择文件'
      uploadLocal: '上传本地图片或视频'
      progress: '上传进度 {{percent}}%'
      completed: '上传完成（100%）'
      failed: '上传失败'
      canceled: '上传已取消'
    }
    validation: {
      facebookStoryNoDes: 'Facebook Story不支持填写描述'
      facebookReelNoImage: 'Facebook Reel不支持上传图片'
      instagramStoryNoDes: 'Instagram Story不支持填写描述'
      instagramReelNoImage: 'Instagram Reel不支持上传图片'
      instagramPostNoVideo: 'Instagram post不支持上传视频'
      titleMaxExceeded: '{{platformName}}标题最多{{maxCount}}字'
      descriptionMaxExceeded: '{{platformName}}描述最多{{maxCount}}字'
      descriptionRequired: '描述是必须的'
      uploadImageOrVideo: '请上传图片或视频'
      uploadImage: '请上传图片'
      uploadVideo: '请上传视频'
      topicMaxExceeded: '{{platformName}}话题最多不能超过{{maxCount}}个'
      topicFormatError: '描述中的话题必须使用空格分割，如："#话题1 #话题2"'
      titleRequired: '标题是必须的'
      topicRequired: '话题是必须的'
      partitionRequired: '您必须选择分区!'
      sourceRequired: '转载时必须填写转载来源!'
      pageRequired: '您必须选择页面!'
      boardRequired: '您必须选择Board!'
      coverSizeError: '封面最小尺寸400*400!'
      imageOnly: '已有图片，仅可继续上传图片，不能上传视频！'
      videoOnly: '已有视频，仅可继续上传视频，不能上传图片！'
      imageVideoMixed: '图片和视频不能混合上传！'
      onlyImageOrVideo: '只能上传图片或视频文件！'
      videoMaxExceeded: '视频上传数量不能大于{{maxCount}}'
      imageMaxExceeded: '图片上传数量不能大于{{maxCount}}'
      instagramImageValidation: 'Instagram Post 图片比例需在 4:5 ~ 1.91:1 范围内。'
      instagramReelAspectRatio: 'Instagram Reel 视频宽高比需在 4:5 ~ 9:16 范围内。'
      facebookReelDuration: 'Facebook Reel视频时长需为3–90秒'
      facebookStoryDuration: 'Facebook Story视频时长需为3–4小时'
      instagramVideoSize: 'Instagram视频大小不能超过100MB'
      instagramReelDuration: 'Instagram Reel视频时长需为5秒–15分钟'
      instagramStoryDuration: 'Instagram Story视频时长需为3–60秒'
      threadsVideoSize: 'Threads视频大小不能超过1GB'
      threadsVideoDuration: 'Threads视频时长需为0秒以上且不超过5分钟'
      threadsImageMin: 'Threads图片至少需要两张'
      pinterestVideoDuration: 'Pinterest视频时长需为4秒–15分钟'
      pinterestVideoSize: 'Pinterest视频大小不能超过1GB'
      tiktokVideoDuration: 'TikTok视频时长需为3秒至10分钟'
      tiktokVideoSize: 'TikTok视频大小不能超过1GB'
      tiktokVideoMinResolution: 'TikTok视频最小分辨率为360x360'
      twitterVideoDuration: 'Twitter视频时长需为0.5秒–140秒'
      twitterVideoSize: 'Twitter视频大小不能超过512MB'
      facebookPostImageSize: 'Facebook Post图片大小不能超过10MB'
      facebookStoryImageSize: 'Facebook Story图片大小不能超过4MB'
      instagramImageSize: 'Instagram图片大小不能超过8MB'
      pinterestImageSize: 'Pinterest图片大小不能超过10MB'
      tiktokImageSize: 'TikTok图片大小不能超过20MB'
      tiktokImageResolution: 'TikTok图片最大分辨率为1080x1920或1920x1080'
      twitterImageSize: 'Twitter图片大小不能超过5MB'
      twitterImageResolution: 'Twitter图片最大分辨率为8192x8192'
      youtubeResolutionSuggestion: '建议视频分辨率：1920×1080（16:9）或 1080×1920（9:16）。'
      youtubeVideoSize: 'YouTube视频大小不能超过256GB'
      youtubeVideoDuration: 'YouTube视频时长不能超过12小时'
      categoryRequired: '您必须选择视频分类！'
      kwaiResolutionSuggestion: '推荐视频分辨率：1080x1920（竖屏）。'
      kwaiDurationSuggestion: '视频时长建议：15秒-3分钟。'
    }
    preview: {
      title: '预览'
      emptyDescription: '在这里看到你的作品预览'
      videoInfo: {
        filename: '文件名'
        format: '格式'
        resolution: '分辨率'
        size: '大小'
        duration: '时长'
      }
    }
    draft: {
      selectDraft: '选择草稿'
      selectDraftGroup: '选择草稿箱组'
      selectDraftItem: '选择草稿'
      noDraftGroups: '暂无草稿箱组'
      noDrafts: '该组暂无草稿'
      backToGroups: '返回草稿箱组'
      selectDraftSuccess: '草稿已应用'
      imageGroup: '图文组'
      videoGroup: '视频组'
      selectLibrary: '选择素材库'
      selectLibraryItem: '选择素材'
      selectLibraryGroup: '选择素材库组'
      noLibraryGroups: '暂无素材库组'
      backToLibraryGroups: '返回素材库组'
      noLibraryItems: '该组暂无素材'
      selectLibrarySuccess: '素材已应用'
    }
    actions: {
      selectMaterial: '选择素材'
      selectDraft: '选择草稿'
      cropCover: '裁剪封面'
      contentModeration: '内容安全检测'
      checkingContent: '检测中...'
      contentSafe: '内容安全'
      riskLevel: '等级:'
      contentUnsafe: '内容不安全'
      preview: '点击查看'
    }
    messages: {
      authFailedRetry: '授权失败，请重试'
      pleaseInputContent: '请先输入内容'
      contentModerationFailed: '内容安全检测失败，请稍后重试'
      contentModerationError: '内容安全检测失败'
      unsupportedPlatformType: '未支持的平台类型'
      platformNotSupportedDirect: '暂不支持 {{platform}} 平台的直接授权'
      facebookAuthFailed: 'Facebook授权失败'
      accountListRefreshed: '账号列表已刷新'
      refreshAccountListFailed: '刷新账号列表失败'
      authFailed: '授权失败'
    }
    badges: {
      offline: '已离线'
      forbidden: '禁'
    }
    tiktok: {
      creatorInfo: '创作者信息'
      privacy: {
        title: '谁可以观看'
        placeholder: '请选择隐私级别'
        public: '公开'
        friends: '朋友'
        private: '仅自己'
      }
      interactions: {
        title: '允许用户'
        comment: '评论'
        duet: '合拍'
        stitch: '拼接'
      }
      commercial: {
        title: '披露视频'
        toggle: '开启以披露此视频推广商品或服务以换取价值。'
        yourBrand: '您的品牌 - 您正在推广自己或自己的业务。此内容将被分类为品牌有机内容。'
        brandedContent: '品牌内容 - 您正在推广另一个品牌或第三方。此内容将被分类为品牌内容。'
      }
      compliance: {
        default: '发布即表示您同意 TikTok 的音乐使用确认。'
        organic: '发布即表示您同意 TikTok 的音乐使用确认。'
        branded: '发布即表示您同意 TikTok 的品牌内容政策音乐使用确认。'
        both: '发布即表示您同意 TikTok 的品牌内容政策音乐使用确认。'
      }
    }
    previewvideo: '预览视频'
    record: {
      metrics: {
        views: '查看数'
        comments: '评论数'
        likes: '点赞数'
        shares: '分享数'
      }
      viewWork: '查看作品'
    }
  }
  'route': {
    home: '首页'
    accounts: '账户'
    publish: '发布'
    hotContent: '热门内容'
    hotContentNew: '热门内容新'
    download: '下载'
    aiTools: 'AI工具'
    tasks: '任务中心'
    interactive: '作品互动'
    engagement: '互动数据'
    dataStatistics: '数据统计'
    navigation: '导航'
    aiRank: 'AI热榜'
  }
  'task': {
    title: '任务中心'
    subtitle: '接受任务，完成任务，获得奖励'
    pendingTasks: '待接受任务'
    acceptedTasks: '已接受任务'
    taskDetails: '任务详情'
    acceptTask: '接受任务'
    completeTask: '完成任务'
    submitTask: '提交任务'
    viewDetails: '查看详情'
    taskProcessing: '任务处理中...'
    acceptingTask: '正在接受任务...'
    publishingTask: '正在发布任务...'
    submittingTask: '正在提交任务...'
    taskCompleted: '任务完成'
    taskStatus: {
      pending: '待完成'
      doing: '已完成'
      accepted: '已接受'
      completed: '已完成'
      rejected: '已拒绝'
      active: '进行中'
      inactive: '已结束'
    }
    taskTypes: {
      video: '视频'
      article: '图文'
      article2: '纯文字'
    }
    platforms: {
      tiktok: 'TikTok'
      youtube: 'YouTube'
      twitter: 'Twitter'
      bilibili: '哔哩哔哩'
      KWAI: '快手'
      douyin: '抖音'
      xhs: '小红书'
      wxSph: '微信视频号'
      wxGzh: '微信公众号'
      facebook: 'Facebook'
      instagram: 'Instagram'
      threads: 'Threads'
      pinterest: 'Pinterest'
    }
    taskInfo: {
      publishTime: '发布时间'
      endTime: '结束时间'
      acceptTime: '接受时间'
      submitTime: '提交时间'
      reward: '奖励'
      type: '类型'
      status: '状态'
      description: '描述'
      account: '发布账号'
      currentRecruits: '已接受'
      maxRecruits: '最大招募'
      people: '人'
      firstSubmission: '首次提交'
    }
    messages: {
      pleaseLoginFirst: '请先登录以查看任务'
      getPendingTasksFailed: '获取待接受任务失败'
      getAcceptedTasksFailed: '获取已接受任务失败'
      acceptTaskSuccess: '接受任务成功！'
      acceptTaskFailed: '接受任务失败'
      submitTaskSuccess: '任务提交成功！'
      submitTaskFailed: '任务提交失败'
      publishTaskFailed: '发布任务失败'
      getTaskDetailFailed: '获取任务详情失败'
      taskProcessFailed: '任务处理失败'
      noPendingTasks: '暂无待接受任务'
      noAcceptedTasks: '暂无已接受任务'
      noTaskDetails: '暂无任务详情'
      loading: '加载中...'
      totalRecords: '共 {{total}} 条记录'
      pageInfo: '第 {{start}}-{{end}} 条，共 {{total}} 条'
      taskInProgress: '任务正在进行中，可以接受'
      taskEnded: '任务已结束'
      acceptedCount: '已接受 {{current}}/{{max}} 人'
    }
    modal: {
      submitTask: '提交任务'
      submitLink: '提交链接'
      submitLinkPlaceholder: '请输入任务完成后的链接'
      submitTip: '请确保您已经完成了任务要求，并提供了正确的提交链接。'
      confirmSubmit: '确认提交'
      cancel: '取消'
      close: '关闭'
      mediaPreview: '媒体预览'
    }
    time: {
      justNow: '刚刚'
      minutesAgo: '{{minutes}}分钟前'
      hoursAgo: '{{hours}}小时前'
      daysAgo: '{{days}}天前'
    }
    accountSelect: {
      title: '选择账号'
      description: '请选择要用于发布任务的账号'
      accountId: '账号ID'
      redirectingToAccounts: '正在跳转到账户页面，请添加频道账号'
    }
  }
  'translation': {
    title: 'AIToEarn官方网站'
    content: '最好用的开源矩阵工具'
  }
  'vip': {
    title: 'PLUS会员'
    description: '开通会员解锁全部功能，立享8种权益'
    activateNow: '立即开通'
    upgrade: '开通会员'
    membership: '会员'
    pleaseLoginFirst: '请先登录'
    paymentOrderCreated: '支付订单创建成功'
    paymentLinkNotFound: '未获取到支付链接'
    createPaymentOrderFailed: '创建支付订单失败'
    createPaymentOrderError: '创建支付订单失败，请稍后重试'
    trialNotice: {
      badge: '🎉 新用户专享'
      description: '选择连续包月或连续包年，可享受7天免费试用期！'
    }
    trialText: {
      month: '前7天免费，之后$15/月'
      year: '前7天免费，之后$120/年'
    }
    badge: {
      onceMonth: '一次性'
      month: '7天免费试用'
      year: '7天免费试用'
      monthOld: '25%优惠'
      yearOld: '50%优惠'
    }
    vipBenefits: {
      exclusiveBadge: '专属标识'
      advancedFeatures: '高级功能'
      memberGift: '会员礼包'
      prioritySupport: '优先支持'
      discount: '优惠折扣'
      unlimitedTime: '无限时长'
      fastExperience: '极速体验'
      morePrivileges: '更多特权'
    }
    plans: {
      onceMonth: '一次性月度'
      month: '月度订阅'
      year: '年度订阅'
    }
    planTitles: {
      month: '月费会员'
      year: '年费会员'
      onceMonth: '月度会员'
    }
    selectDuration: '选择开通时长'
    autoRenewal: '自动续订，随时取消'
    priceUnits: {
      month: '/月'
      year: '/年'
    }
    subscriptionManagement: '订阅管理'
    subscriptionPlanManagement: '订阅计划管理'
    subscriptionPlans: '订阅计划'
    purchaseHistory: '购买记录'
    myMembership: '我的会员'
    basicMembership: '基础会员'
    validUntil: '有效期至'
    activatedAutoRenewalPlans: '已开通自动续费套餐'
    activatedAutoRenewalPlansno: '未开通自动续费套餐'
    noAutoRenewalItems: '你还没有开通自动续费项目哦'
    viewMorePlans: '查看更多套餐'
    continuousAnnual: '连续包年'
    oneTimePurchase: '购买'
    alipayPayment: '支付宝支付'
    noMoreContent: '没有内容了'
    previousPage: '上一页'
    nextPage: '下一页'
    pageInfo: '第 {current} 页，共 {total} 页'
    continuousMember: '连续会员'
    singleMember: '单月会员'
    autoRenewalEnabled: '自动续费已开启'
    autoRenewalDisabled: '自动续费未开启'
    nextRenewalDate: '下次续费时间'
    membershipExpires: '有效期至'
    currentPlan: '当前计划'
    modal: {
      title: '免费试用3天会员'
      highlight: ''
      choosePlan: '选择合适你的套餐，或直接'
      buyPoints: '购买积分'
      pointsDetail: '积分详情'
      vipInfo: {
        details: '详情'
        subscription: '订阅管理'
        planType: '计划'
        monthly: '连续包月PLUS会员'
        monthly2: '月度会员'
        yearly: '连续包年PLUS会员'
        yearly2: '年度会员'
        singleMonth: '单月会员'
        trial: '试用中'
        cancelled: '已退订'
        expireTime: '到期时间'
        xufeiTime: '续费时间'
        remainingPoints: '剩余积分'
        buyPoints: '购买积分'
      }
      tabs: {
        yearly: '连续包年'
        monthly: '连续包月'
        once: '单月购买'
      }
      savings: {
        yearly: '省50%'
        monthly: '省25%'
      }
      free: {
        title: '免费'
        price: '0'
        period: '/月'
        forever: '永久'
        currentPlan: '免费计划'
        freePlan: '免费计划'
        points: '60 积分/月'
        features: {
          dailyPoints: '发布：抖音、小红书、视频号、快手、哔哩哔哩、微信公众号、TikTok、YouTube、Facebook、Instagram、Threads、X (Twitter)、Pinterest'
          maxPoints: '互动：抖音、小红书、Facebook、Instagram、Threads'
          videos: 'AI工具：核心模型池（gpt-5系列、gemini-2.5-pro/flash、qwen-vl-max、gpt-image-1、FLUX.1 Kontext、seedream/seededit、md2card、萤火卡等）'
          images: 'Sora-2 & Nano Banana: 有限使用（按积分/限额）'
          storage: '内容和评论搜索、智能互动'
        }
      }
      plans: {
        goumai: '购买'
        yearly: {
          title: '年度会员'
          bestValue: '最超值'
          price: '12'
          period: '/月'
          originalPrice: '$300/年'
          button: '$144/年 省50%'
          points: '760 积分/月（含60签到积分）'
          description: '每月最多150+次视频生成'
          features: {
            contentReview: 'Sora-2：免费且无限'
            dailyPoints: 'Nano Banana：免费且无限'
            multiModel: '历史内容导入'
            textToVideo: '免费计划的所有功能'
            aiGeneration: '无限频道连接'
            noWatermark: '内容和评论搜索、智能互动'
          }
        }
        monthly: {
          title: '月度会员'
          price: '19'
          period: '/月'
          originalPrice: '$25/月'
          button: '$19/月 省25%'
          points: '760 积分/月（含60签到积分）'
          description: '每月最多150+次视频生成'
        }
        once: {
          title: '一次性月度'
          price: '25'
          period: '/月'
          button: '$25/月'
          points: '760 积分/月（含60签到积分）'
          description: '每月最多150+次视频生成'
          storage: '5G 存储空间'
        }
      }
      trial: '7天免费试用'
      cancelAnytime: '包年可随时取消'
      cancelMonthly: '包月可随时取消'
    }
    points: {
      title: '积分详情'
      current: '当前积分'
      remaining: '剩余积分'
      subscribed: '订阅积分'
      recharged: '充值积分'
      gifted: '赠送积分'
      validity: '积分有效期'
      tabs: {
        all: '全部'
        spend: '消耗'
        earn: '获得'
      }
      noData: '没有内容了'
      disclaimer: '仅展示近1个月明细，数据更新可能有延时 积分规则'
      recordChange: '积分变动'
      recordTypes: {
        recharge: '充值'
        consume: '消耗'
        gift: '赠送'
        refund: '退款'
        expire: '过期'
        adjust: '调整'
      }
    }
    recharge: {
      title: '购买积分'
      current: '当前积分'
      price: '每1000积分售价15美元'
      amount: '购买积分'
      total: '总价'
      buyNow: '立即购买'
      range: '1K-50K'
      unit: '积分'
    }
  }
  'wallet': {
    title: '我的钱包'
    columns: {
      userName: '真实姓名'
      mail: '邮箱'
      account: '账号'
      type: '类型'
      phone: '手机号'
      cardNum: '身份证号'
      actions: '操作'
    }
    types: {
      ZFB: '支付宝'
      WX_PAY: '微信支付'
    }
    actions: {
      create: '新增账户'
      edit: '编辑'
      delete: '删除'
      deleteConfirm: '确认删除该钱包账户？'
      confirm: '确认'
      cancel: '取消'
    }
    dialogs: {
      createTitle: '新增钱包账户'
      editTitle: '编辑钱包账户'
    }
    form: {
      userId: '用户ID'
      userIdPlaceholder: '自动填充当前用户ID'
      mail: '邮箱'
      mailPlaceholder: '请输入邮箱'
      mailInvalid: '请输入有效的邮箱地址'
      userName: '真实姓名'
      userNamePlaceholder: '请输入真实姓名（可选）'
      account: '账号'
      accountPlaceholder: '请输入收款账号'
      cardNum: '身份证号'
      cardNumPlaceholder: '请输入身份证号（可选）'
      phone: '手机号'
      phonePlaceholder: '请输入绑定手机号（可选）'
      type: '类型'
      typePlaceholder: '请选择类型'
      required: '必填项'
    }
    messages: {
      createSuccess: '创建成功'
      updateSuccess: '更新成功'
      deleteSuccess: '删除成功'
    }
  }
  'youtube': {
    youtubeAuth: 'YouTube 授权'
    authDescription: '请输入您的邮箱地址以获取 YouTube 授权'
    email: '邮箱'
    enterEmail: '请输入邮箱地址'
    authorize: '授权'
    pleaseEnterEmail: '请输入邮箱地址'
    invalidEmail: '请输入有效的邮箱地址'
    authFailed: '授权失败，请稍后重试'
    checkAuth: '检查授权'
    notAuthorized: '未授权'
    uploadVideo: '上传视频'
    needAuthFirst: '首先需要授权'
    uploadFailed: '上传失败'
    uploadSuccess: '上传成功'
    checkFailed: '检查失败'
    alreadyAuthorized: '已授权'
  }
}

export default Resources
