import { CronExpression } from '@nestjs/schedule'

export const PUBLISHING_SCHEDULED_TASK_CRON_EXPRESSION = CronExpression.EVERY_10_SECONDS
export const IMMEDIATE_PUBLISH_TOLERANCE_SECONDS = 10 * 1000
export const PUBLISHING_STATUS_WATCHDOG_CRON_EXPRESSION = CronExpression.EVERY_10_MINUTES
export const PUBLISHING_CALLBACK_TIMEOUT_MS = 2 * 60 * 60 * 1000
export const PUBLISHING_STATUS_WATCHDOG_BATCH_SIZE = 50
export const MEDIA_PROCESSING_POLL_INTERVAL_MS = 30 * 1000
export const MEDIA_PROCESSING_POLL_ATTEMPTS = Math.ceil(PUBLISHING_CALLBACK_TIMEOUT_MS / MEDIA_PROCESSING_POLL_INTERVAL_MS)
