name: Release Browser Automation Worker

on:
  push:
    tags:
      - 'v*.*.*' # 触发条件：推送版本标签，如 v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build and prune browser-automation-worker
        run: |
          pnpm nx build browser-automation-worker --no-cloud
          echo "Build completed, checking output directory..."
          ls -la dist/apps/browser-automation-worker/
          echo "Checking package.json dependencies..."
          cat dist/apps/browser-automation-worker/package.json

      - name: Create release package
        run: |
          cp .npmrc dist/apps/browser-automation-worker/
          tar -czf browser-automation-worker-${{ github.ref_name }}.tar.gz -C dist/apps/browser-automation-worker .
          echo "Package created: browser-automation-worker-${{ github.ref_name }}.tar.gz"
          ls -la browser-automation-worker-*.tar.gz

      - name: Generate Release Notes
        id: generate_release_notes
        run: |
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 `git rev-list --tags --skip=1  --max-count=1`)
          echo "Previous tag: $PREVIOUS_TAG"
          LOG=$(git log $PREVIOUS_TAG..${{ github.ref_name }} --pretty=format:"* %s (%h)")
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo -e "## What's Changed\n\n$LOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --title "Browser Automation Worker ${{ github.ref_name }}" \
            --notes "${{ env.CHANGELOG }}" \
            browser-automation-worker-${{ github.ref_name }}.tar.gz
